org.sonar.ide.eclipse.core/src/org/sonar/ide/eclipse/core/internal/SonarProperties.java
org.sonar.ide.eclipse.core/src/org/sonar/ide/eclipse/core/internal/jobs/AnalyzeProjectJob.java
org.sonar.ide.eclipse.core/src/org/sonar/ide/eclipse/core/internal/servers/SonarServer.java

Did a quick functional test, looks good

Change preview mode to issues mode

---

org.sonarlint.eclipse.core/plugin.xml
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/adapter/DefaultSonarLintFileAdapterFactory.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/adapter/DefaultSonarLintProjectAdapterFactory.java
org.sonarlint.eclipse.ui/plugin.xml
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/adapter/DefaultSonarLintProjectContainerAdapterFactory.java

Some of the class names contained a minor typo. I took the liberty to fix the names.

Fixed typo - renamed "Adater" classes to "Adapter" and updated references accordingly

---

org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/CompatibilityUtils.java
org.sonarlint.eclipse.ui/plugin.xml
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintImages.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/issues/IssueDescriptionField.java

and fix rendering when using the group by severity feature

SLE-124 Disable display of issue type on Eclipse < Neon

---

README.md

> You can also download it directly from here. - https://bintray.com/sonarsource/SonarLint-for-Eclipse/download_file?file_path=releases%2Forg.sonarlint.eclipse.site-3.2.0.201706271328.zip

README - offline install option

---

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/AbstractNotificationPopup.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/GradientColors.java

https://groups.google.com/forum/#!topic/sonarlint/NTwR6oU2VYI

SLE-156 Updated how gradient calculations are done for popup considering the theme colors

---

README.md

Updated archive of releases link

Updated ReadMe.MD with new download site

---

its/org.sonarlint.eclipse.its/src/org/sonarlint/eclipse/its/AbstractSonarLintTest.java
its/org.sonarlint.eclipse.its/src/org/sonarlint/eclipse/its/ConnectedModeTest.java
its/org.sonarlint.eclipse.its/src/org/sonarlint/eclipse/its/ConnectedModeWithOrgaTest.java
its/org.sonarlint.eclipse.its/src/org/sonarlint/eclipse/its/NotificationsCheckboxTest.java

Because of the release of the alpha1, ITs are broken.

Handle version X.Y.Z-alphaW

---

its/org.sonarlint.eclipse.its/src/org/sonarlint/eclipse/its/AbstractSonarLintTest.java
its/org.sonarlint.eclipse.its/src/org/sonarlint/eclipse/its/StandaloneAnalysisTest.java
its/org.sonarlint.eclipse.its/src/org/sonarlint/eclipse/its/bots/ProjectExplorerBot.java
org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/adapter/DefaultSonarLintAdapterFactoryTest.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/resources/DefaultSonarLintProjectAdapter.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/resource/ISonarLintProject.java

The IT `StandaloneAnalysisTest.shouldAnalysePhp` was randomly failing.

Fix random test failure php

---

its/org.sonarlint.eclipse.its/src/org/sonarlint/eclipse/its/RulesConfigurationTest.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/RuleParameterPanel.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/RulesConfigurationPart.java

SLE-365 UI bug fixes

---

its/org.sonarlint.eclipse.its/src/org/sonarlint/eclipse/its/RulesConfigurationTest.java

I think you missed some `waitForJobsToComplete` calls

Fix rule param ITs

---

its/target-platform-2020-06/target-platform-its-2020-06-dev.target
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/StandaloneEngineFacade.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/connected/ConnectedEngineFacade.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/connected/IConnectedEngineFacade.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AnalyzeConnectedProjectJob.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/tracking/ServerIssueUpdater.java
pom.xml

There was a possible NPE when an analysis was executed while the engine was restarted

Make engine facade more thread/null safe

---

org.sonarlint.eclipse.site/pom.xml
pom.xml

This requires a new feature of Tycho 2.3-SNAPSHOT

Sign third party plugins in our p2 repo

---

azure-pipelines.yml

Please review our [contribution guidelines](https://github.com/SonarSource/sonarlint-eclipse/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines:

BUILD-1123 Update signing key

---

org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/SonarLintUtils.java

Bump Java Analyzer to newest version, run tests on the changed / added rules: S1142 / S6539
Bump Python Analyzer to newest version, run tests on the added rule: S6542

SLE-611, SLE-610: Update Java, Python Analyzer

---

org.sonarlint.eclipse.site/pom.xml

Tested manually on Eclipse 2020-06

SLE-608 Sign artifacts with jarsigner from JDK 11

---

org.sonarlint.eclipse.core/pom.xml

Update the analyzer for Python and Text. Nothing too fancy.

SLE-627,SLE-631: Analyzer update

---

its/META-INF/MANIFEST.MF
its/src/org/sonarlint/eclipse/its/RuleDescriptionViewTest.java
its/src/org/sonarlint/eclipse/its/RulesConfigurationTest.java
its/target-platforms/commons.target
org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/jobs/AnalyzeStandaloneProjectJobTest.java
org.sonarlint.eclipse.core/pom.xml

Analyzer updates for XML, Java, PHP and JavaScript / TypeScript.

SLE-639,SLE-640,SLE-644,SLE-654: Analyzer updates

---

org.sonarlint.eclipse.core/pom.xml

Update of Java / Python analyzer, tested against changes.

SLE-660,SLE-662: Analyzer update

---

org.sonarlint.eclipse.core/pom.xml

It is faster now, nothing else to say 😃

SLE-677: XML analyzer update

---

its/projects/java/maven2/.classpath
its/projects/java/maven2/.project
its/projects/java/maven2/.settings/org.eclipse.jdt.core.prefs
its/projects/java/maven2/.settings/org.eclipse.m2e.core.prefs
its/projects/java/maven2/pom.xml
its/projects/java/maven2/src/main/java/hello/Hello.java
its/projects/java/maven2/src/main/java/hello/Hello2.java
its/src/org/sonarlint/eclipse/its/SonarQubeConnectedModeTest.java
its/src/org/sonarlint/eclipse/its/reddeer/wizards/MarkIssueAsDialog.java
org.sonarlint.eclipse.ui/plugin.xml

Marking an issue in connected mode: Trying to resolve an issue with insufficient permissions and then with administrator rights.

SLE-681: Integration tests for marking issues

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/resources/DefaultSonarLintProjectsProvider.java

Do not offer the binding of technical projects.

SLE-628: No binding suggestion for technical projects

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/TriggerType.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/ConfigScopeSynchronizer.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/connected/ConnectedEngineFacade.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/connected/IConnectedEngineFacade.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/connected/IServerEventListener.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AnalyzeConnectedProjectJob.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/TaintIssuesUpdateAfterSyncJob.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/TaintIssuesUpdateOnFileOpenedJob.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/tracking/ServerIssueUpdater.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/vcs/VcsService.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintServerEventListener.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintUiPlugin.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/PeriodicStoragesSynchronizerJob.java

As discussed, I am not super happy about all those changes. I would have preferred to move most of the logic to the backend, but it will take longer than expected. So this is a kind of workaround in the meantime.

SLE-659 SLE-633 Fix branch and taint synchronization

---

target-platforms/commons.target

Update SLCORE to the released artifact.

SLE-683: SLCORE 9.0 update

---

.cirrus.yml
its/projects/java/maven2/.classpath
its/projects/java/maven2/.project
its/projects/java/maven2/.settings/org.eclipse.jdt.core.prefs
its/projects/java/maven2/.settings/org.eclipse.m2e.core.prefs
its/projects/java/maven2/pom.xml
its/projects/java/maven2/src/main/java/hello/Hello.java
its/projects/java/maven2/src/main/java/hello/Hello2.java
its/src/org/sonarlint/eclipse/its/SonarQubeConnectedModeTest.java
its/src/org/sonarlint/eclipse/its/reddeer/wizards/MarkIssueAsDialog.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/connected/ConnectedEngineFacade.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/connected/IConnectedEngineFacade.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/PeriodicStoragesSynchronizerJob.java

Marking an issue in connected mode: Trying to resolve an issue with insufficient permissions and then with administrator rights. Now on Cirrus CI!

SLE-681: Integration tests for marking issues (#497)

---

org.sonarlint.eclipse.feature/feature.properties
org.sonarlint.eclipse.ui/about.properties

For uniform license information on all the Sonar products, including SonarLint for Eclipse

Update copyright and SonarLint website

---

org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/markers/MarkerUtilsTest.java
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/SonarLintMarkerUpdater.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/markers/MarkerUtils.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/tracking/CombinedTrackable.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/tracking/Trackable.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintImages.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/DisplayGlobalConfigurationRuleDescriptionJob.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/DisplayProjectRuleDescriptionJob.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/rule/RuleDetailsPanel.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/rule/RuleHeaderPanel.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/RuleDescriptionWebView.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/issues/IssueDescriptionField.java
target-platforms/commons.target

Using Sonar Java analyzer dogfooding version.
Additionally, show issue severity / type or clean code attribute / impacts in the Rule Description view instead of the rule values.
@damien-urruty-sonarsource: The failing IT is okey for now, I'll fix it on the common branch, this will be easier!

SLE-690: Added issue marker support

---

its/pom.xml
pom.xml

This release fixes some issues occurring with local development and the Maven-Eclipse integration we were facing.

Update to Tycho 4.0.1

---

its/pom.xml
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/SonarLintMarkerUpdater.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/markers/MarkerUtils.java
org.sonarlint.eclipse.ui/plugin.xml
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintImages.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/issues/IssueDescriptionField.java

Grouping for Impact and Severity (Legacy) is now available for the On-the-fly / Report / Taint Vulnerability views.

SLE-695: Grouping for new and old CCT

---

its/src/org/sonarlint/eclipse/its/reddeer/preferences/SonarLintPreferences.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/preferences/SonarLintGlobalConfiguration.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/Messages.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/documentation/SonarLintDocumentation.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/messages.properties
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/preferences/SonarLintPreferencePage.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/preferences/SonarLintPreferencesInitializer.java

This is only the small part of the workspace-wide preference added.

SLE-723: Added global preference for issue period

---

org.sonarlint.eclipse.core/pom.xml

SonarText, JavaScript / TypeScript, HTML, Python.

Analyzer updates

---

org.sonarlint.eclipse.core/pom.xml

SLE-739: Java analyzer update

---

its/pom.xml
pom.xml

So it is not in the MMF branch, reducing the mess.

NO-JIRA: Update Maven parent POM

---

org.sonarlint.eclipse.core/pom.xml

They just released another version of the JS/TS analyzer, therefore an additional PR ...

SLE-754: JS/TS analyzer update

---

org.sonarlint.eclipse.core/pom.xml

They just released another version of the SonarText analyzer, therefore an additional PR ...

SLE-755: SonarText analyzer update

---

org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.pydev/META-INF/MANIFEST.MF
org.sonarlint.eclipse.pydev/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

As we cant push to master anymore ...

Prepare for next development iteration

---

org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.pydev/META-INF/MANIFEST.MF
org.sonarlint.eclipse.pydev/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

For the upcoming SLE patch release (fixing the artifact certificates).

NO-JIRA: Prepare for patch release

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/markers/MarkerUtils.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/SonarLintUtils.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/command/AbstractIssueCommand.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/command/AbstractResolvedCommand.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/command/MarkAsResolvedCommand.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/command/OpenInBrowserCommand.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/command/ReOpenResolvedCommand.java

Additionally, add more debug logs when adaption is not possible.

SLE-765: Prefer adaption to ISonarLintFile

---

target-platforms/commons.target

Update for the analyzer properties: The logic is now the same as for SonarQube / SonarCloud on parsing the property values.

NO-JIRA: Update SLCORE

---

org.sonarlint.eclipse.feature/feature.xml

First, we built it, now we ship it. I definitely did not forget to add this here ...

Also ship pydev sub-plugin

---

.cirrus.yml

Certificate moving to general location to be reused.

BUILD-4122: Moving certificate

---

org.sonarlint.eclipse.core/pom.xml

Embedded language analyzer updates

---

org.sonarlint.eclipse.core/pom.xml

SLE-770: JS/TS analyzer update

---

org.sonarlint.eclipse.core/pom.xml

Last minute Java analyzer update.

SLE-772: Java analyzer update

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/tracking/PersistentLocalIssueStore.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/NodeJsManager.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/BindingsView.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/BindingsViewDecorator.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/command/AbstractIssueCommand.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/BackendProgressJobScheduler.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/OpenIssueInEclipseJob.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/RulesConfigurationPage.java

This will help to migrate to RPC

Stop using the logger from SLCORE

---

its/pom.xml
pom.xml
target-platforms/commons.target

SLE-773: Update protobuf dependency

---

org.sonarlint.eclipse.core/pom.xml

Python / Java / JavaScript & TypeScript analyzer update.

SLE-788,SLE-789,SLE-790: Analyzer update

---

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/command/HelpOnIconsCommand.java

The Clean Code attributes pages were recently improved in the Docs.
This PR updates the destination URL.
A redirect will be requested in the interim.

update new Clean Code landing URL

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/LogListener.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintUiPlugin.java

These issues were not displayed on the Sloop PR, sadly. But now they're correctly fixed, and others are accepted.

NO-JIRA: Fix SQ issues on master

---

org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.pydev/META-INF/MANIFEST.MF
org.sonarlint.eclipse.pydev/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

It was decided that, due to the changes in this version regarding the Extension Points the plug-ins provide, this version will be a major version.
In order to not mess up the history on Next and to not lose any issues, this is done now and not earlier!

NO-JIRA: Bump up version for release

---

.cirrus.default.yml
pom.xml

This speeds up the local builds and also some of the CI tasks

SLE-807: CycloneDx only on necessary build steps

---

.cirrus.default.yml

This issue came in from the PR rebasing.

NO-JIRA: Fix Cirrus Mend step

---

.cirrus.default.yml
.cirrus/Dockerfile
.cirrus/publish-dogfood-site.sh

Use the builder container
Install AWS CLI, gettext-base (envsubst)
Fix Cirrus artifact download URL

BUILD-3457 fix dogfooding

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java
pom.xml
target-platforms/commons.target

This will set the telemetry service initially as a feature flag.

SLE-829: Telemetry handled via feature flag

---

org.sonarlint.eclipse.core/pom.xml

This includes updates of the following analyzers:
- Java
- JS/TS
- PHP
- Python
- HTML
- SonarText

Analyzer update

---

.sonarlint/connectedMode.json

Share the information for SLE amongst contributors! :smile:

NO-JIRA: Shared Connected Mode configuration

---

pom.xml
target-platforms/commons.target

NO-JIRA: Use latest SLCORE

---

.cirrus.default.yml
.cirrus.ibuilds.yml

To reduce the network usage with Repox while speeding up the the Cirrus CI pipeline.

SLE-869: Use Cirrus CI cache for orchestrator

---

org.sonarlint.eclipse.core/pom.xml

The SonarJava analyzer now consists of two plug-ins: The already existing `sonar-java-plugin` and the new `sonar-java-symbolic-execution-plugin`.

SLE-879: Java analyzer update + new plug-in

---

.cirrus.default.yml
.cirrus.ibuilds.yml
.cirrus/cirrus_promote_maven
.cirrus/regular_mvn_build_deploy_analyze

SLE-894: Decommission Burgr

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/resources/DefaultSonarLintProjectsProvider.java

As Eclipse PDE decided to change the project name.

SLE-901: Change project name check

---

.cirrus.default.yml
.cirrus.ibuilds.yml

NO-JIRA: Move to uniform Slack notifications

---

its/src/org/sonarlint/eclipse/its/AbstractSonarLintTest.java
its/src/org/sonarlint/eclipse/its/SecretsTest.java
its/src/org/sonarlint/eclipse/its/SonarQubeConnectedModeTest.java
its/src/org/sonarlint/eclipse/its/StandaloneSharedConnectedModeTest.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/SonarLintNotifications.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintEclipseHeadlessRpcClient.java

The notification about detected secrets was enhanced in SLCORE and, therefore, now features the information also in the IDE if the project is still open.

SLE-867: Secrets detected notification based on projects

---

its/pom.xml
pom.xml

NO-JIRA: Update Parent POM

---

org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html

Includes:
- Java analyzer
- Secrets / Text
- Release Notes

Pre release analyzer update

---

.cirrus.default.yml
its/README.md
its/org.sonarlint.eclipse.its.connected.sc/pom.xml
its/org.sonarlint.eclipse.its.connected.sc/src/org/sonarlint/eclipse/its/connected/sc/SonarCloudConnectedModeTest.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/ProjectBindingWizardIsOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/wizards/ProjectBindingWizard.java

Reworked the old (and never used) IT and embedded it into the new environment.

SLE-911: Implement first test with SonarCloud

---

org.sonarlint.eclipse.core/pom.xml

[SLE-933](https://sonarsource.atlassian.net/browse/SLE-933)
Updates to the
- Java
- Python
- PHP
- Secrets
analyzers
[SLE-933]: https://sonarsource.atlassian.net/browse/SLE-933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-912,SLE-913,SLE-929,SLE-933: Analyzer updates

---

its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/StandaloneAnalysisTest.java
its/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-935](https://sonarsource.atlassian.net/browse/SLE-935)
Preparation for release
[SLE-935]: https://sonarsource.atlassian.net/browse/SLE-935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-935 Update Release Notes / Parent POM / SLCORE

---

.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
docs/PULL_REQUEST_TEMPLATE.md

SLE-942 Jira integration: Use repo vault token

---

its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/OpenInIdeTest.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/AbstractDialogOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/AbstractDialogWithParameterOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/AbstractDialogWithTwoParametersOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/AbstractViewOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/ConfirmConnectionCreationDialogOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/ConfirmManualAnalysisDialogOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/EnhancedWithConnectedModeInformationDialogOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/FileNotFoundDialogOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/FixSuggestionAvailableDialogOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/FixSuggestionUnavailableDialogOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/OpenInIdeDialogOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/ProjectSelectionDialogOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/ShareConnectedModeConfigurationDialogOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/SonarLintTaintVulnerabilitiesViewOpened.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/dialogs/ConfirmConnectionCreationDialog.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/dialogs/FixSuggestionAvailableDialog.java
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/backend/SonarLintEclipseRpcClient.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/NoBindingSuggestionFoundPopup.java
pom.xml
target-platforms/commons-build.target

[SLE-925](https://sonarsource.atlassian.net/browse/SLE-925)
I had to update SLCORE first (in a separate commit).
This ticket does not include any changes to the production code but cleaning up and refactoring the IT wait conditions.
[SLE-925]: https://sonarsource.atlassian.net/browse/SLE-925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-925: Move IT wait conditions to generics

---

its/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintEclipseHeadlessRpcClient.java
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-959](https://sonarsource.atlassian.net/browse/SLE-959)
For the upcoming release of SonarLint for Eclipse 10.8!
[SLE-959]: https://sonarsource.atlassian.net/browse/SLE-959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-959: Update SLCORE / Parent POM / Release Notes

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-961](https://sonarsource.atlassian.net/browse/SLE-961)
[SLE-961]: https://sonarsource.atlassian.net/browse/SLE-961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-961: Prepare for next development iteration

---

org.sonarlint.eclipse.core/pom.xml

[SLE-973](https://sonarsource.atlassian.net/browse/SLE-973)
[SLE-974](https://sonarsource.atlassian.net/browse/SLE-974)
[SLE-975](https://sonarsource.atlassian.net/browse/SLE-975)
[SLE-984](https://sonarsource.atlassian.net/browse/SLE-984)
Updating the following analyzers:
- Java
- XML
- Python
- Secrets (SonarText)
[SLE-973]: https://sonarsource.atlassian.net/browse/SLE-973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-974]: https://sonarsource.atlassian.net/browse/SLE-974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-975]: https://sonarsource.atlassian.net/browse/SLE-975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-984]: …

SLE-973,SLE-974,SLE-975,SLE-984: Analyzer update

---

its/pom.xml
org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml

[SLE-960](https://sonarsource.atlassian.net/browse/SLE-960)
[SLE-960]: https://sonarsource.atlassian.net/browse/SLE-960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-960: Update Parent POM / Release Notes

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-987](https://sonarsource.atlassian.net/browse/SLE-987)
[SLE-987]: https://sonarsource.atlassian.net/browse/SLE-987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-987: Prepare for next development iteration

---

org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-991](https://sonarsource.atlassian.net/browse/SLE-991)
[SLE-991]: https://sonarsource.atlassian.net/browse/SLE-991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-991: Update release notes, SLCORE

---

its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/AbstractSonarQubeConnectedModeTest.java
its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/SonarQubeConnectedModeTest.java
org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/markers/MarkerUtilsTest.java
org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/tracking/SonarLintMarkerUpdaterTest.java
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/SonarLintMarkerUpdater.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/markers/MarkerUtils.java
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/DisplayProjectRuleDescriptionJob.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/rule/AbstractRuleHeaderPanel.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/rule/LegacyRuleHeaderPanel.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/rule/RuleDetailsPanel.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/rule/RuleHeaderPanel.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/RuleDescriptionWebView.java
pom.xml
target-platforms/commons-build.target

[SLE-983](https://sonarsource.atlassian.net/browse/SLE-983)
For SQ-S 10.8+ handle the different modes correctly in Connected Mode. For SQ-S 9.9 LTA handle the Standard mode correctly as there hasn't been any MQR mode yet. For SQ-S 10.0-10.7 handle the MQR mode as it was the default for these versions. For Standalone Mode handle MQR mode.
[SLE-983]: https://sonarsource.atlassian.net/browse/SLE-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-983: Handle Standard and MQR mode correctly

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java

[SLE-958](https://sonarsource.atlassian.net/browse/SLE-958)
Enable (and simplify) the process of passing system properties / options that are used by Sloop from the configuration passed to the IDE.
[SLE-958]: https://sonarsource.atlassian.net/browse/SLE-958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-958: Pass system properties / options to Sloop

---

its/README.md
its/org.sonarlint.eclipse.its.standalone/its.ibuilds.product
its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/FileExclusionsTest.java
org.sonarlint.eclipse.buildship/src/org/sonarlint/eclipse/buildship/internal/GradleUtils.java
org.sonarlint.eclipse.core/schema/projectHierarchyProvider.exsd
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/FileSystemSynchronizer.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/DefaultPreAnalysisContext.java
org.sonarlint.eclipse.jdt/src/org/sonarlint/eclipse/jdt/internal/JdtUtils.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/BindingsView.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/hotspots/HotspotsView.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/AbstractOpenInEclipseJob.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/OpenIssueInEclipseJob.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/ShareProjectBindingJob.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/ProjectBoundPopup.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/util/PlatformUtils.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/locations/IssueLocationsView.java
target-platforms/README.md
target-platforms/latest-java-11_e424.target
wss-unified-agent.config

[SLE-971](https://sonarsource.atlassian.net/browse/SLE-971)
Use codespell to fix typos in documentation, comments, etc.
Reference is #750
[SLE-971]: https://sonarsource.atlassian.net/browse/SLE-971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-971: Fix typos

---

org.sonarlint.eclipse.core/pom.xml

[SLE-994](https://sonarsource.atlassian.net/browse/SLE-994)
[SLE-995](https://sonarsource.atlassian.net/browse/SLE-995)
[SLE-1004](https://sonarsource.atlassian.net/browse/SLE-1004)
[SLE-1007](https://sonarsource.atlassian.net/browse/SLE-1007)
[SLE-1008](https://sonarsource.atlassian.net/browse/SLE-1008)
[SLE-1009](https://sonarsource.atlassian.net/browse/SLE-1009)
- Java
- JS/TS
- PHP
- Python
- HTML
- XML
[SLE-994]: https://sonarsource.atlassian.net/browse/SLE-994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-995]: https://sonarsource.atlassian.net/browse/SLE-995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1004]: https://sonarsource.atlassian.net/browse/SLE-1004?atlOrigin=eyJpIjoiNWR …

SLE-994,SLE-995,SLE-1004,SLE-1007,SLE-1008,SLE-1009: Analyzer updates

---

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/FileSystemSynchronizer.java
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
pom.xml
target-platforms/commons-build.target

[SLE-1002](https://sonarsource.atlassian.net/browse/SLE-1002)
[SLE-1010](https://sonarsource.atlassian.net/browse/SLE-1010)
:cool: 
[SLE-1002]: https://sonarsource.atlassian.net/browse/SLE-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1010]: https://sonarsource.atlassian.net/browse/SLE-1010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1002,SLE-1010: Adapt to the repackaging and update the SonarText analyzer

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1011](https://sonarsource.atlassian.net/browse/SLE-1011)
[SLE-1011]: https://sonarsource.atlassian.net/browse/SLE-1011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1011: JS/TS analyzer update

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1012](https://sonarsource.atlassian.net/browse/SLE-1012)
[SLE-1012]: https://sonarsource.atlassian.net/browse/SLE-1012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1012: Prepare for next development iteration

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1016](https://sonarsource.atlassian.net/browse/SLE-1016)
[SLE-1019](https://sonarsource.atlassian.net/browse/SLE-1019)
[SLE-1016]: https://sonarsource.atlassian.net/browse/SLE-1016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1019]: https://sonarsource.atlassian.net/browse/SLE-1019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1016,SLE-1019: JS/TS, Python analyzer update

---

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-1013](https://sonarsource.atlassian.net/browse/SLE-1013)
[SLE-1013]: https://sonarsource.atlassian.net/browse/SLE-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1013: Update release notes / SLCORE

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1022](https://sonarsource.atlassian.net/browse/SLE-1022)
[SLE-1022]: https://sonarsource.atlassian.net/browse/SLE-1022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1022: Prepare for next development iteration

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1024](https://sonarsource.atlassian.net/browse/SLE-1024)
Update analyzer of:
- Java
- JS/TS/CSS
- PHP
- HTML
- Text & Secrets
- CFamily
[SLE-1024]: https://sonarsource.atlassian.net/browse/SLE-1024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1024,SLE-1025,SLE-1026,SLE-1027,SLE-1028,SLE-1031: Analyzer update

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1035](https://sonarsource.atlassian.net/browse/SLE-1035)
Includes analyzer updates for:
- Java/JSP
- PHP
- Python
[SLE-1035]: https://sonarsource.atlassian.net/browse/SLE-1035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1035,SLE-1036,SLE-1038: Analyzer update

---

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-1023](https://sonarsource.atlassian.net/browse/SLE-1023)
[SLE-1023]: https://sonarsource.atlassian.net/browse/SLE-1023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1023: Update release notes / SLCORE

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1042](https://sonarsource.atlassian.net/browse/SLE-1042)
[SLE-1042]: https://sonarsource.atlassian.net/browse/SLE-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1042: Prepare for next development iteration

---

org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/tracking/SonarLintMarkerUpdaterTest.java
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AnalyzeProjectJob.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/markers/MarkerUtils.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/CanceledException.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/JobUtils.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/SonarLintUtils.java
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
pom.xml
target-platforms/commons-build.target

[SLE-1049](https://sonarsource.atlassian.net/browse/SLE-1049)
Update SLCORE with the latest master before addressing the changes, then remove most code and replace `CanceledException` by a local implementation.
[SLE-1049]: https://sonarsource.atlassian.net/browse/SLE-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1049: Remove dependency on SonarLint Core Commons module

---

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintImages.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/console/SonarLintConsole.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/ErrorPopup.java
pom.xml
target-platforms/commons-build.target

[SLE-580](https://sonarsource.atlassian.net/browse/SLE-580)
To raise awareness with users that an error is exceptional and should be raised with us on the Community Forum.
[SLE-580]: https://sonarsource.atlassian.net/browse/SLE-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-580: Notify users about errors to raise on the Forum

---

.cirrus.default.yml
its/README.md
its/org.sonarlint.eclipse.its.connected.sc/src/org/sonarlint/eclipse/its/connected/sc/SonarCloudConnectedModeTest.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/ZeroIssuesOnProject.java
pom.xml
target-platforms/commons-build.target

[SLE-1039](https://sonarsource.atlassian.net/browse/SLE-1039)
The option to log in with username/password will be removed from SonarQube Cloud in the future.
[SLE-1039]: https://sonarsource.atlassian.net/browse/SLE-1039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1039: Token for SonarQube Cloud ITs

---

its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/SonarQubeConnectedModeTest.java
org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-1043](https://sonarsource.atlassian.net/browse/SLE-1043)
[SLE-1043]: https://sonarsource.atlassian.net/browse/SLE-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1043: Update release notes, SLCORE

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1053](https://sonarsource.atlassian.net/browse/SLE-1053)
[SLE-1053]: https://sonarsource.atlassian.net/browse/SLE-1053?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1053: Prepare for next development iteration

---

org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/engine/connected/ConnectedEngineFacadeManagerTest.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintEclipseHeadlessRpcClient.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/connected/ConnectionFacade.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/connected/ConnectionManager.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/Messages.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/assist/AssistCreatingAutomaticConnectionJob.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/AbstractConnectionWizard.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/EditNotificationsWizard.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/OrganizationProvider.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/ServerConnectionModel.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/ServerConnectionWizard.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/messages.properties

[SLE-1059](https://sonarsource.atlassian.net/browse/SLE-1059)
After username/password authentication was deprecated over a year ago and the UI logic was dropped a couple of months ago, this will now get removed completely.
[SLE-1059]: https://sonarsource.atlassian.net/browse/SLE-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1059: Remove username/password logic completely

---

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
pom.xml
target-platforms/commons-build.target

[SLE-1067](https://sonarsource.atlassian.net/browse/SLE-1067)
In order to potentially find issues after changes in SLCORE that can raise previously unknown errors ([commit on SLCORE](https://github.com/SonarSource/sonarlint-core/commit/554765257d217062cc8f9c68f60a212fd07def95)).
[SLE-1067]: https://sonarsource.atlassian.net/browse/SLE-1067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1067 Update SLCORE

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java

[SLE-1062](https://sonarsource.atlassian.net/browse/SLE-1062)
Keep "SonarLint" in the user agent for the compatibility with older SQ-S versions.
[SLE-1062]: https://sonarsource.atlassian.net/browse/SLE-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1062: Include new brand name in User Agent

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/documentation/SonarLintDocumentation.java

[DOC-1835](https://sonarsource.atlassian.net/browse/DOC-1835)
[DOC-1835]: https://sonarsource.atlassian.net/browse/DOC-1835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOC-1835 rebrand docs URL

---

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/backend/SonarLintEclipseRpcClient.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/InvalidTokenPopup.java

[SLE-1064](https://sonarsource.atlassian.net/browse/SLE-1064)
A new notification for users having an invalid token. This way less error messages are shown to the user and SonarLint CORE won't try to reach out for connections that do not work anyway until the user changes the credentials (token).
[SLE-1064]: https://sonarsource.atlassian.net/browse/SLE-1064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1064: Notification on invalid credentials

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1070](https://sonarsource.atlassian.net/browse/SLE-1070)
(╯°□°)╯︵ ┻━┻
[SLE-1070]: https://sonarsource.atlassian.net/browse/SLE-1070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1070: Java analyzer update

---

org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-1054](https://sonarsource.atlassian.net/browse/SLE-1054)
[SLE-1054]: https://sonarsource.atlassian.net/browse/SLE-1054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1054: Update release notes, SLCORE

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1069](https://sonarsource.atlassian.net/browse/SLE-1069)
[SLE-1069]: https://sonarsource.atlassian.net/browse/SLE-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1069: Revert analyzer update

---

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
pom.xml
target-platforms/commons-build.target

[SLE-1081](https://sonarsource.atlassian.net/browse/SLE-1081)
To the latest development iteration artifact to dogfood the Git native blaming and its performance impact.
[SLE-1081]: https://sonarsource.atlassian.net/browse/SLE-1081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1081 Update SLCORE

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java

[SLE-1072](https://sonarsource.atlassian.net/browse/SLE-1072)
[SLE-1072]: https://sonarsource.atlassian.net/browse/SLE-1072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1072: Enable monitoring of SLCORE

---

.cirrus/Dockerfile

[SLE-1082](https://sonarsource.atlassian.net/browse/SLE-1082)
[SLE-1082]: https://sonarsource.atlassian.net/browse/SLE-1082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1082: Update Node.js to 22 LTS

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1087](https://sonarsource.atlassian.net/browse/SLE-1087)
[SLE-1074](https://sonarsource.atlassian.net/browse/SLE-1074)
[SLE-1091](https://sonarsource.atlassian.net/browse/SLE-1091)
[SLE-1089](https://sonarsource.atlassian.net/browse/SLE-1089)
[SLE-1088](https://sonarsource.atlassian.net/browse/SLE-1088)
Analyzer updates for:
- JS/TS/CSS
- PHP
- Python
- HTML
- XML
[SLE-1087]: https://sonarsource.atlassian.net/browse/SLE-1087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1074]: https://sonarsource.atlassian.net/browse/SLE-1074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1091]: https://sonarsource.atlassian.net/browse/SLE-1091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …

SLE-1087,SLE-1074,SLE-1091,SLE-1089,SLE-1088: Analzyer update

---

org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-1077](https://sonarsource.atlassian.net/browse/SLE-1077)
[SLE-1077]: https://sonarsource.atlassian.net/browse/SLE-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1077: Update release notes, SLCORE

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1100](https://sonarsource.atlassian.net/browse/SLE-1100)
[SLE-1100]: https://sonarsource.atlassian.net/browse/SLE-1100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1100: Prepare for next development iteration

---

.github/workflows/PullRequestClosed.yml

[SLE-1116](https://sonarsource.atlassian.net/browse/SLE-1116)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SLE-1116]: https://sonarsource.atlassian.net/browse/SLE-1116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1116 Autoclose issues created by Jira integration

---

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/EditNotificationsWizard.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/ServerConnectionModel.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/ServerConnectionWizard.java

[SLE-1108](https://sonarsource.atlassian.net/browse/SLE-1108)
[SLE-1108]: https://sonarsource.atlassian.net/browse/SLE-1108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1108 Stop checking if smart notifications are supported

---

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
pom.xml
target-platforms/commons-build.target

[SLE-1118](https://sonarsource.atlassian.net/browse/SLE-1118)
To check that the latest changes are not breaking anything.
[SLE-1118]: https://sonarsource.atlassian.net/browse/SLE-1118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1118 Update SLCORE

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1107](https://sonarsource.atlassian.net/browse/SLE-1107)
[SLE-1110](https://sonarsource.atlassian.net/browse/SLE-1110)
Updates for:
- Python
- C/C++ (CFamily)
[SLE-1107]: https://sonarsource.atlassian.net/browse/SLE-1107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1110]: https://sonarsource.atlassian.net/browse/SLE-1110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1107,SLE-1110: Analyzer update

---

org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-1099](https://sonarsource.atlassian.net/browse/SLE-1099)
[SLE-1099]: https://sonarsource.atlassian.net/browse/SLE-1099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1099: Update release notes, SLCORE

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1114](https://sonarsource.atlassian.net/browse/SLE-1114)
[SLE-1114]: https://sonarsource.atlassian.net/browse/SLE-1114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1114: Prepare for next development iteration

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1135](https://sonarsource.atlassian.net/browse/SLE-1135)
[SLE-1135]: https://sonarsource.atlassian.net/browse/SLE-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1135 Update CFamily analyzer to 6.65.0.81949

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1126](https://sonarsource.atlassian.net/browse/SLE-1126)
[SLE-1128](https://sonarsource.atlassian.net/browse/SLE-1128)
Updates for:
- Python
- PHP
[SLE-1126]: https://sonarsource.atlassian.net/browse/SLE-1126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1128]: https://sonarsource.atlassian.net/browse/SLE-1128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1126,SLE-1128: Analyzer update

---

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/AboutPropertyPage.java

[SLE-1127](https://sonarsource.atlassian.net/browse/SLE-1127)
Update telemetry sample in the preferences and make sure that the tooltip is shown. The tooltip is now attached to a new text that is highlighted and more visible to the users.
[SLE-1127]: https://sonarsource.atlassian.net/browse/SLE-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1127 Update telemetry sample in the preferences

---

its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/AbstractSonarQubeConnectedModeTest.java
its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/OpenInIdeTest.java
its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/SonarQubeConnectedModeTest.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/dialogs/MarkIssueAsDialog.java

[SLE-771](https://sonarsource.atlassian.net/browse/SLE-771)
The "Mark Issue as ..." feature test was ignored a while ago because it was flaky, this should fix it.
[SLE-771]: https://sonarsource.atlassian.net/browse/SLE-771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-771: Remove unused test and fixed ignored ones

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1132](https://sonarsource.atlassian.net/browse/SLE-1132)
[SLE-1132]: https://sonarsource.atlassian.net/browse/SLE-1132?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1132 Update SonarJava analyzer to 8.11.0.38440

---

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-1115](https://sonarsource.atlassian.net/browse/SLE-1115)
> [!WARNING]
> I also updated the Sonar Java Symbolic Execution plug-in as this was missed when implementing the corresponding ticket.
[SLE-1115]: https://sonarsource.atlassian.net/browse/SLE-1115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1115: Prepare release

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1151](https://sonarsource.atlassian.net/browse/SLE-1151)
[SLE-1151]: https://sonarsource.atlassian.net/browse/SLE-1151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1151: Prepare for next development iteration

---

its/pom.xml
pom.xml

[SLE-1155](https://sonarsource.atlassian.net/browse/SLE-1155)
This is only a build dependency.
[SLE-1155]: https://sonarsource.atlassian.net/browse/SLE-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1155: Update Eclipse Tycho

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1154](https://sonarsource.atlassian.net/browse/SLE-1154)
[SLE-1156](https://sonarsource.atlassian.net/browse/SLE-1156)
[SLE-1162](https://sonarsource.atlassian.net/browse/SLE-1162)
Contains the analyzer updates for:
- XML
- Java
- JS/TS/CSS
[SLE-1154]: https://sonarsource.atlassian.net/browse/SLE-1154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1156]: https://sonarsource.atlassian.net/browse/SLE-1156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1162]: https://sonarsource.atlassian.net/browse/SLE-1162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1154,SLE-1156,SLE-1162: Analyzer updates

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AnalyzeProjectJob.java
pom.xml
target-platforms/commons-build.target

[SLE-1163](https://sonarsource.atlassian.net/browse/SLE-1163)
[SLE-1163]: https://sonarsource.atlassian.net/browse/SLE-1163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1163 Update to the latest SLCORE

---

org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-1152](https://sonarsource.atlassian.net/browse/SLE-1152)
[SLE-1152]: https://sonarsource.atlassian.net/browse/SLE-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1152: Update release notes, SLCORE

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1168](https://sonarsource.atlassian.net/browse/SLE-1168)
[SLE-1168]: https://sonarsource.atlassian.net/browse/SLE-1168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1168: Prepare for next development iteration

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1170](https://sonarsource.atlassian.net/browse/SLE-1170)
[SLE-1170]: https://sonarsource.atlassian.net/browse/SLE-1170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1170: Prepare for next development iteration

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1175](https://sonarsource.atlassian.net/browse/SLE-1175)
[SLE-1173](https://sonarsource.atlassian.net/browse/SLE-1173)
[SLE-1175]: https://sonarsource.atlassian.net/browse/SLE-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1173]: https://sonarsource.atlassian.net/browse/SLE-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1175 SLE-1173 Analyzer updates

---

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-1169](https://sonarsource.atlassian.net/browse/SLE-1169)
[SLE-1169]: https://sonarsource.atlassian.net/browse/SLE-1169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1169 Update Release Notes / Parent POM / SLCORE

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1177](https://sonarsource.atlassian.net/browse/SLE-1177)
[SLE-1177]: https://sonarsource.atlassian.net/browse/SLE-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1177: Prepare for next development iteration

---

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
pom.xml
target-platforms/commons-build.target

[SLE-1153](https://sonarsource.atlassian.net/browse/SLE-1153)
[SLE-1153]: https://sonarsource.atlassian.net/browse/SLE-1153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1153: Update SLCORE including Git Worktree support

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintEclipseHeadlessRpcClient.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/AbstractConnectionWizard.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/OrganizationProvider.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/ServerConnectionModel.java

[SLE-1174](https://sonarsource.atlassian.net/browse/SLE-1174)
[SLE-1174]: https://sonarsource.atlassian.net/browse/SLE-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1174 Remove deprecated code

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1176](https://sonarsource.atlassian.net/browse/SLE-1176)
[SLE-1183](https://sonarsource.atlassian.net/browse/SLE-1183)
[SLE-1183](https://sonarsource.atlassian.net/browse/SLE-1183)
[SLE-1176]: https://sonarsource.atlassian.net/browse/SLE-1176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1183]: https://sonarsource.atlassian.net/browse/SLE-1183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1183]: https://sonarsource.atlassian.net/browse/SLE-1183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1176 SLE-1183 SLE-1183 Analyzer updates

---

org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-1178](https://sonarsource.atlassian.net/browse/SLE-1178)
[SLE-1178]: https://sonarsource.atlassian.net/browse/SLE-1178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1178 Update Release Notes / Parent POM / SLCORE

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1188](https://sonarsource.atlassian.net/browse/SLE-1188)
[SLE-1188]: https://sonarsource.atlassian.net/browse/SLE-1188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1188 Prepare for next development iteration

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1186](https://sonarsource.atlassian.net/browse/SLE-1186)
[SLE-1187](https://sonarsource.atlassian.net/browse/SLE-1187)
[SLE-1193](https://sonarsource.atlassian.net/browse/SLE-1193)
[SLE-1186]: https://sonarsource.atlassian.net/browse/SLE-1186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1187]: https://sonarsource.atlassian.net/browse/SLE-1187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1193]: https://sonarsource.atlassian.net/browse/SLE-1193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1186, SLE-1187, SLE-1193 Update JS/TS/CSS, Java and C/C++ analyzers

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1194](https://sonarsource.atlassian.net/browse/SLE-1194)
[SLE-1194]: https://sonarsource.atlassian.net/browse/SLE-1194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1194 Update SonarPHP analyzer to 3.46.0.13151

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/FileSystemSynchronizer.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java

[SLE-1199](https://sonarsource.atlassian.net/browse/SLE-1199)
[SLE-1199]: https://sonarsource.atlassian.net/browse/SLE-1199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1199 Synchronize the file system from a background thread

---

org.sonarlint.eclipse.core/pom.xml

[SLE-1195](https://sonarsource.atlassian.net/browse/SLE-1195)
[SLE-1200](https://sonarsource.atlassian.net/browse/SLE-1200)
[SLE-1201](https://sonarsource.atlassian.net/browse/SLE-1201)
[SLE-1195]: https://sonarsource.atlassian.net/browse/SLE-1195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1200]: https://sonarsource.atlassian.net/browse/SLE-1200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1201]: https://sonarsource.atlassian.net/browse/SLE-1201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1195, SLE-1200, SLE-1201 Analyzer updates

---

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
pom.xml
target-platforms/commons-build.target

[SLE-1224](https://sonarsource.atlassian.net/browse/SLE-1224)
[SLE-1224]: https://sonarsource.atlassian.net/browse/SLE-1224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1224 Update to latest SLCORE

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/documentation/SonarLintDocumentation.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/TokenWizardPage.java
pom.xml
target-platforms/commons-build.target

[SLE-1215](https://sonarsource.atlassian.net/browse/SLE-1215)
[SLE-1215]: https://sonarsource.atlassian.net/browse/SLE-1215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1215 Track links from SQ:IDE to SQ:Cloud

---

org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/rule/RuleDetailsPanel.java

[SLE-1240](https://sonarsource.atlassian.net/browse/SLE-1240)
[SLE-1241](https://sonarsource.atlassian.net/browse/SLE-1241)
[SLE-1243](https://sonarsource.atlassian.net/browse/SLE-1243)
[SLE-1244](https://sonarsource.atlassian.net/browse/SLE-1244)
[SLE-1229](https://sonarsource.atlassian.net/browse/SLE-1229)
[SLE-1247](https://sonarsource.atlassian.net/browse/SLE-1247)
[SLE-1247](https://sonarsource.atlassian.net/browse/SLE-1249)
Wrapping fix:
[SLE-1240]: https://sonarsource.atlassian.net/browse/SLE-1240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1241]: https://sonarsource.atlassian.net/browse/SLE-1241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1243]: …

SLE-1240 SLE-1241 SLE-1243 SLE-1244 SLE-1229 SLE-1247 SLE-1249 Hardening 11.13

---

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html
pom.xml
target-platforms/commons-build.target

[SLE-1250](https://sonarsource.atlassian.net/browse/SLE-1250)
[SLE-1253](https://sonarsource.atlassian.net/browse/SLE-1253)
[SLE-1250]: https://sonarsource.atlassian.net/browse/SLE-1250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-1253]: https://sonarsource.atlassian.net/browse/SLE-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1250 SLE-1253 Update SonarText, SonarJS and SLCORE

---

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/NotificationsWizardPage.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/ServerConnectionModel.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/NewerVersionAvailablePopup.java
pom.xml
target-platforms/commons-build.target

[SLE-1257](https://sonarsource.atlassian.net/browse/SLE-1257)
[SLE-1257]: https://sonarsource.atlassian.net/browse/SLE-1257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1257, SLE-1258 fix rebranding leftovers

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1264](https://sonarsource.atlassian.net/browse/SLE-1264)
[SLE-1264]: https://sonarsource.atlassian.net/browse/SLE-1264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1264 Prepare for next development iteration

---

its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/AbstractSonarLintTest.java
its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/views/SonarLintConsole.java
org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/jobs/AnalyzeStandaloneProjectJobTest.java
org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/resources/SonarLintProjectConfigurationManagerTest.java
org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/tracking/SonarLintMarkerUpdaterTest.java
org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/utils/DurationUtilsTest.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/SonarLintLogger.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/LogListener.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/SonarLintUtilsLogOutput.java
org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/sentry/SentryLogListener.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintUiPlugin.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/console/SonarLintConsole.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/console/SonarLintConsolePageParticipant.java
org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/preferences/SonarLintPreferencesInitializer.java

[SLE-1228](https://sonarsource.atlassian.net/browse/SLE-1228)
[SLE-1228]: https://sonarsource.atlassian.net/browse/SLE-1228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1228 drop show analyzer logs setting

---

org.sonarlint.eclipse.buildship/META-INF/MANIFEST.MF
org.sonarlint.eclipse.buildship/pom.xml
org.sonarlint.eclipse.cdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.cdt/pom.xml
org.sonarlint.eclipse.core.tests/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core.tests/pom.xml
org.sonarlint.eclipse.core/META-INF/MANIFEST.MF
org.sonarlint.eclipse.core/pom.xml
org.sonarlint.eclipse.feature/feature.xml
org.sonarlint.eclipse.feature/pom.xml
org.sonarlint.eclipse.jdt/META-INF/MANIFEST.MF
org.sonarlint.eclipse.jdt/pom.xml
org.sonarlint.eclipse.m2e/META-INF/MANIFEST.MF
org.sonarlint.eclipse.m2e/pom.xml
org.sonarlint.eclipse.site/pom.xml
org.sonarlint.eclipse.sloop.linux.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.aarch64/pom.xml
org.sonarlint.eclipse.sloop.linux.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.linux.x64/pom.xml
org.sonarlint.eclipse.sloop.macosx.aarch64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.aarch64/pom.xml
org.sonarlint.eclipse.sloop.macosx.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.macosx.x64/pom.xml
org.sonarlint.eclipse.sloop.no-arch/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.no-arch/pom.xml
org.sonarlint.eclipse.sloop.windows.x64/META-INF/MANIFEST.MF
org.sonarlint.eclipse.sloop.windows.x64/pom.xml
org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF
org.sonarlint.eclipse.ui/pom.xml
pom.xml

[SLE-1287](https://sonarsource.atlassian.net/browse/SLE-1287)
[SLE-1287]: https://sonarsource.atlassian.net/browse/SLE-1287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1287 Prepare next dev iteration

---

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/documentation/SonarLintDocumentation.java

[SLE-1291](https://sonarsource.atlassian.net/browse/SLE-1291)
[SLE-1291]: https://sonarsource.atlassian.net/browse/SLE-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SLE-1291 update link to Server docs
