SonarSource/sonarlint-eclipse

org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/markers/MarkerUtilsTest.java, org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/tracking/MarkerUpdaterTest.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AnalyzeProjectJob.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/markers/FlatTextRange.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/markers/MarkerUtils.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/markers/TextRange.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/tracking/IssueTrackable.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/tracking/MarkerUpdater.java
Note: the PR target is not `master`, but `feature/issue-tracking`.
What should work:
- Issue tracking in standalone or connected mode, except matching by checksum (text range hash and line hash are broken at the moment)
- Hide resolved issues
- Correct marker severity display in issues view
- Correct marker display in editor view
- Correct matching by text-range-hash (only local issues have)
- Tests (travis) should pass
Regressions (prevent merging to `master`):
- Trigger analysis only on file open and on explicit command (currently Save triggers it too)
- Make `IssueTrackerCache` persistent, initialized at startup
- Clear tracking data on binding change
Other TODO:
- Improve the initialization of the per-project `IssueTracker` instances: should happen on project import / open event
- …
=> Fixes for issue tracking display and tests

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintUiPlugin.java
Simple (dumb?) solution. Other alternatives considered:
- Make `Server.getConfig` wrap `StorageException` in custom exception, to catch instead of generic `IllegalStateException`. Drawback: adding API
- Run in a `Job`. Drawback: unusual to run something as a job something fast, just to defer crash in another thread
=> Do not crash when fail to subscribe to notifications

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/telemetry/SonarLintTelemetry.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/CheckForUpdatesJob.java
As per [Platform Plug-in Developer Guide > Programmer's Guide > Runtime overview > Concurrency infrastructure > Reporting progress](http://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fruntime_jobs_progress.htm&cp=2_0_3_5_0) :
> What if your job is a low-level implementation detail that you don't want to show to users? You can flag your job as a system job. A system job is just like any other job, except the corresponding UI support will not set up a progress view or show any other UI affordances associated with running a job. If your job is not either directly initiated by a user, or a periodic task that can be configured by a user, then your job should be a system job.
So I propose to make "telemetry" and "updates check" a system jobs.
Before this …
=> SLE-199 Hide "telemetry" and "updates check" from "progress" view

its/org.sonarlint.eclipse.its/src/org/sonarlint/eclipse/its/utils/JobHelpers.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AbstractAnalyzeProjectJob.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AbstractSonarProjectJob.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AnalyzeChangedFilesJob.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AnalyzeProjectsJob.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AsyncServerMarkerUpdaterJob.java
Only run actual resource change (i.e. marker updates) within a workspace
operation to avoid blocking the autobuild during long-running analyses.
https://community.sonarsource.com/t/sonarlint-analysis-blocks-autobuild/10483
I don't think the changes can be unit tested (sensibly).
=> Reduced scope of workspace operations

org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/telemetry/SonarLintTelemetryTest.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/SonarLintCorePlugin.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/resources/ProjectsProviderUtils.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/server/ServersManager.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/telemetry/SonarLintTelemetry.java
We report SonarCloud usage if at least one project is bound and opened.
Previously we could report SonarCloud usage if a server connection to SC was created but no project was bound.
=> SLE-352 Improve SonarCloud usage report in telemetry

org.sonarlint.eclipse.feature/feature.xml, org.sonarlint.eclipse.site/category.xml, org.sonarlint.eclipse.site/pom.xml, pom.xml
This way we make sure the Mylyn dependency is always present, even on IDEs where it is not present by default and the update site might be hard to reach
=> SLE-354 Embed mylyn dependencies in sonarlint feature.

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/RuleParameterPanel.java
FYI @henryju the behavior is a bit different than in IJ: in both platforms when a rule is not active, the rule parameters panel is disabled. On IJ tooltips are displayed anyway but not on Eclipse. You have to activate the rule first before the tooltips are shown. I think it is sufficient and as it is the platform behavior I'm not sure we can do something
=> SLE-376 Show rule parameter description as a tooltip over input components

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AbstractAnalyzeProjectJob.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AnalyzeStandaloneProjectJob.java
I'm not totally happy with this change. I did not find a way to run only one analysis when settings are changed.
As a workaround, I'm now ensuring that rules configuration is taken at the last possible moment, and I also tried to limit the workspace locking as much as possible.
=> Try to make concurrent analysis more reliable

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/flowlocations/SonarLintFlowAnnotator.java
I did a test on Neon.3, and we are already using `textEditor.getDocumentProvider().getDocument(textEditor.getEditorInput())` in other places so I'm pretty confident with the fix.
=> SLE-396 Fix NPE in Neon

pom.xml
The BOM is only required under CI and its generation takes ages under Win OS, then let's skip it by default when running under windows family OS.
=> BUILD-1578 skip BOM under windows os

pom.xml
- BUILD-1634 skip cyclonedx on local build
Execute CycloneDX only when built by CI.
Remove profile skipping CycloneDX under Windows
Workaround conflict between makeAggregateBom + inherited=false and clean triggered by tycho-p2-plugin: exclude bom from clean
=> BUILD-1634 only exec cyclonedx on root project and under CI

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/connected/ConnectedEngineFacade.java
Since recent changes in SLCORE, the connected engine can be used by several threads at the same time
=> SLE-525 Remove synchronization when using the connected engine

its/projects/js/js-simple/lambda.yaml, its/src/org/sonarlint/eclipse/its/StandaloneAnalysisTest.java
No change in production code as the new YAML language was automatically enabled. We instead list languages to disable.
=> SLE-549 Support analysis of JS in YAML files

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/connected/ConnectedEngineFacade.java, target-platforms/build.target
The only case where this could happen is if the engine is not started. We throw an error instead
=> SLE-558 Do not assume master is the main branch name

.github/workflows/release.yml
Upgrade to gh-action_release v5 (5.0.2)
- this includes onboarding on the Vault https://github.com/SonarSource/re-terraform-aws-vault/pull/440
- https://github.com/SonarSource/gh-action_release/pull/73 migrates the P2 update site to new binaries
=> BUILD-2507 upgrade to gh-action_release v5 (5.0.2)

its/pom.xml, pom.xml
Added a new environment to both Maven main projects (parent & ITS) to support macOS on ARM64 (M1 / M2) from the command line and within the specific Eclipse IDE.
This was tested with [Amazon Corretto 11](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/macos-install.html) and [Amazon Correto 17](https://docs.aws.amazon.com/corretto/latest/corretto-17-ug/macos-install.html) installed on macOS 13.3.1 and not the builtin Java 17 JRE in Eclipse.
Due to the only available Eclipse IDEs for macOS on ARM64 being the ones coming with Java 17 (4.22), the integration tests can not be run on the oldest Eclipse version supported in `its/target-platforms/oldest.target`.
Therefore a profile was added as an exception until the oldests supported Eclipse version is 4.22 or higher.
=> macOS ARM64 Support

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/issues/TaintVulnerabilitiesView.java
The Eclipse view "SonarLint Taint Vulnerabilities" now shows the same information text as the one shown in IntelliJ (except the terminology: In Eclipse it's a view, in IntelliJ it's a tab of the tool window).
Streamlining both information labels also required a change to the corresponding GitHub wiki pages. The minor changes can be viewed at:
- [SonarLint for Eclipse GitHub Wiki page "Taint Vulnerabilites"](https://github.com/SonarSource/sonarlint-eclipse/wiki/Taint-Vulnerabilities)
- [SonarLint for IntelliJ GitHub Wiki page "Taint Vulnerabilites"](https://github.com/SonarSource/sonarlint-intellij/wiki/Taint-Vulnerabilities)
A screenshot of the pages prior to the change can be found as an attachment to the Jira issue [SLE-612](https://sonarsource.atlassian.net/browse/SLE-612)!
[SLE-612]: …
=> SLE-612: Streamline IDE / GH Wiki content for Taint Vulnerabilities

org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/jdt/internal/JdtUtilsTest.java, org.sonarlint.eclipse.jdt/src/org/sonarlint/eclipse/jdt/internal/JdtUtils.java
The new property "sonar.java.enablePreview" will be set automatically based on the specific project settings. If the project setting is unavailable or disabled (default or on purpose by user), the property value will be set to "False", otherwise to "True".
=> SLE-614: Sonar property based on project settings

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/SonarLintUtils.java
Languages are added to `sonarlint-core`, so every new language must be disabled. This change simpliefies the process and disables the the addition of an unsupported language by accedentially updating `sonarlint-core` without checking for new languages.
=> SLE-615: Whitelist enabled languages

its/src/org/sonarlint/eclipse/its/RuleDescriptionViewTest.java, its/src/org/sonarlint/eclipse/its/reddeer/conditions/RuleDescriptionViewContainsText.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AbstractSonarGlobalConfigurationJob.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AbstractSonarJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/DisplayGlobalConfigurationRuleDescriptionJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/DisplayProjectRuleDescriptionJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/RulesConfigurationPart.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/util/SonarLintRuleBrowser.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/RuleDescriptionWebView.java
Switched to the new RulesService, therefore this PR is more or less a WIP. Updated the background jobs for loading the SonarLintRuleBrowser content to differ based on project / global configuration level.
The only issue I'm currently facing is the following: Having a project opened which is bound to my local SQ instance, when analyzing a file of that project and the local SQ instance is down, the `SonarLintBackendService.getEffectiveRuleDetails` will hang in the background job as it awaits its own timeout. It doesn't know for now, that the connection might not be available at all.
=> SLE-619: Switch to new RulesService

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/hotspots/HotspotsView.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/rule/RuleDescriptionPanel.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/rule/RuleDetailsPanel.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/util/BrowserUtils.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/util/HTMLUtils.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/util/SonarLintWebView.java
Syntax highlighting shall be also available for the security hotspot view even though it does not match with the implementation of the normal rule description panel shown in the "SonarLint Rule Description" and settings menu view.
Load `SonarSource/sonarlint-language-server` into the `runtime-EclipseApplication`, connect to **next.sonarqube.com** and open the Security Hotspot (e.g. *java:S2245*).
=> SLE-651: Hotspots with syntax highlighting

.github/workflows/release.yml
Validate future 5.0.8 release of gh-action_release that includes CloudFront invalidation of the S3 cache.
=> BUILD-2809 try gh-action_release 5.0.8

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/command/MarkAsResolvedCommand.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/dialog/MarkAsResolvedDialog.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/dialog/package-info.java
This adds a dialog for the muting issues action based on the IntelliJ implementation. Allowed issue transitions are added dynamically based on the permissions check prior.
Also the `CompletableFuture` instances from the `IssueService` method invocations are currently not functional as I did not want to change anything by mistake, I'm mostly testing with SLLS.
Not yet tested but in the end when everything is ready we should add integration tests both for muting an issue and a taint vulnerability!
=> SLE-667: Dialog for muting issues

its/src/org/sonarlint/eclipse/its/AbstractSonarLintTest.java, its/src/org/sonarlint/eclipse/its/reddeer/preferences/FileAssociationsPreferences.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/NodeJsManager.java, target-platforms/commons.target
Automatic detection of Node.js on macOS does not work when added to $PATH from the user shell configuration.
Additional changes to ITs finally make the tests run on macOS. This issue of file associations was fixed with this commit.
=> SLE-626: Node.js on macOS

.cirrus.yml
The toolchains installed on the custom container are needed.
=> BUILD-3064 fix Mend task

.cirrus.yml
`jfrog rt upload` requires `--build=$BUILD_NAME/$BUILD_NUMBER`
=> BUILD-3064 JFrog CLI updated options

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/BindingsView.java
When a project is closed (or reopened) or deleted, the SonarLint Bindings view should be updated to not include irrelevant projects which might lead to errors when trying to change the binding of it. This does not include importing a project.
=> SLE-616: Update binding view based on project

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/dialog/MarkAsResolvedDialog.java
The label uses the OS native element and cannot show line breaks on Windows (not even Windows-specific line breaks).
=> Fix RadioButton label

org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/ui/internal/properties/RulesConfigurationPartTest.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/engine/StandaloneEngineFacade.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/telemetry/SonarLintTelemetry.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/RuleParameterPanel.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/RulesConfigurationPage.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/RulesConfigurationPart.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/rule/RuleDetailsPanel.java
*SonarLint for Eclipse* does not rely on the deprecated methods from `StandaloneSonarLintEngine` from *SonarLint Core* anymore.
=> SLE-694: Remove deprecated methods

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintUiPlugin.java
Definitely run in the UI thread! I was assuming that due to the `StartupJob` it would automatically run on the UI thread, but that was not the case: The build passed without any issues, and manual testing was done as well, but noticed in validation with other Eclipse versions that it is a "flaky" issue based on Eclipse deciding where to run stuff.
=> NO-JIRA: Eclipse user survey

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintPostBuildListener.java
As mentionned in the IncrementalProjectBuilder.CLEAN_BUILD documentation 'Resource deltas are not applicable for this kind of build.'
=> Avoid resourceChanged computation for IncrementalProjectBuilder.CLEAN_BUILD

.cirrus.yml
When running the "unit" tests we face the issue that on failures prior to running the tests (setting up environment) or after (tearing down environment) the log is not printed to the console but to the specific workspace file.
@matemoln while just forwarding the file content to the console was possible, it was very messy as the log can be quite huge.
=> BUILD-3911: Upload JUnit Plug-in Test logs

org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/preferences/SonarLintGlobalConfigurationTest.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/resources/SonarLintProperty.java
We don't want to have extra analyzer properties containing some form of white spaces (which can cause issues), therefore we strip everything when saving them.
=> SLE-745: Strip extra analyzer properties

org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/tracking/ProjectIssueTrackerTest.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/tracking/ProjectIssueTracker.java
Handle the corner case in which a file with issues cannot be matched to server issues because the file itself does not comply with the server path.
=> SLE-747: IDE to server path matching failure

its/src/org/sonarlint/eclipse/its/AbstractSonarLintTest.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/preferences/SonarLintGlobalConfiguration.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/backend/SonarLintEclipseClient.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/documentation/SonarLintDocumentation.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/SoonUnsupportedPopup.java
When connected to a soon unsupported SonarQube server (second to last LTS) we display a notification to the user with the information on what and why. The user can acknowledge the information to not show it again, then he will also be forwarded to the SonarLint documentation page on that matter.
Testing was done manually and is ensured by the integration tests targeting the **Oldest** target platform.
=> SLE-720: Show soon unsupported SQ connection notification

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintUiPlugin.java
The current survey ends, therefore we remove it from being triggered on the user side. The code remains (commented out) in place for later use and/or when we refactor the survey mechanism to work via the SonarLint website.
=> NO-JIRA: Remove Eclipse user survey

its/src/org/sonarlint/eclipse/its/SonarQubeConnectedModeTest.java, its/src/org/sonarlint/eclipse/its/reddeer/wizards/ServerConnectionWizard.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/UsernamePasswordWizardPage.java
Users should only use tokens when setting up / changing connections in the future. Until then we provide them with information that the method is going to be deprecated in the future!
=> SLE-752: Deprecate username/password authentication

org.sonarlint.eclipse.jdt/src/org/sonarlint/eclipse/jdt/internal/JdtUtils.java
This is based on the issue mentioned in this [Community Forum Thread](https://community.sonarsource.com/t/nullpointerexception-org-eclipse-core-resources-iresource-getlocation-is-null/105303). When a Java project classpath file contains invalid library entries we should log them but not fail the analysis.
=> SLE-784: Don't fail on incorrect classpath

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/SonarLintMarkerUpdater.java
This is based on the issue mentioned in this [Community Forum Thread](https://community.sonarsource.com/t/errors-and-seemingly-successful-analysis/105232). It is nice that we log the stack trace and the text range but we don't log the file/resource and the circumstances it is happening on - making it hard to debug such cases where it is not clear if the issue is coming from SonarLint or one of the language analyzers.
=> NO-JIRA: Log information about incomplete markers

.cirrus.yml, its/src/org/sonarlint/eclipse/its/OpenInIdeTest.java, its/src/org/sonarlint/eclipse/its/StandaloneAnalysisTest.java
iBuilds are failing as we are depending on external dependencies for this axis (Eclipse IDE). iBuilds axis is removed and will be managed in a separate ticket to have an axis we can trigger manually for testing.
This separate ticket is [SLE-786](https://sonarsource.atlassian.net/browse/SLE-786).
[SLE-786]: https://sonarsource.atlassian.net/browse/SLE-786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix Cirrus CI

its/pom.xml, its/src/org/sonarlint/eclipse/its/AbstractSonarQubeConnectedModeTest.java, its/src/org/sonarlint/eclipse/its/OpenInIdeTest.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/backend/SonarLintEclipseClient.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/assist/AbstractAssistCreatingConnectionJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/assist/AssistCreatingAutomaticConnectionJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/assist/AssistCreatingManualConnectionJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/assist/ConfirmConnectionCreationDialog.java, target-platforms/commons.target
When running "Open in IDE" with SonarQube 10.4+, we can automatically set up connected mode. This helps the user to have a minimal solution for configuration.
Integration tests were added to the already existing "Open in IDE" tests, and the whole test suite was overhauled to only create a project once on SQ and to run Maven only once in order to save [precious](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRs65wa-OyfSBvrvzmqkQfUR4fz44neeZniGmOIXy07A&s) build time.
=> SLE-791: Automated connected mode setup

its/src/org/sonarlint/eclipse/its/AbstractSonarLintTest.java, its/src/org/sonarlint/eclipse/its/StandaloneAnalysisTest.java, its/src/org/sonarlint/eclipse/its/reddeer/preferences/GeneralWorkspaceBuildPreferences.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/preferences/SonarLintGlobalConfiguration.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintNoAutomaticBuildWarningService.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintUiPlugin.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/NoAutomaticBuildWarningPopup.java
When the automatic build of the workspace is disabled, some rules might not yield accurate results compared to when the automatic build of the workspace is enabled.
=> SLE-408: Notification about analysis accuracy

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/documentation/SonarLintDocumentation.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AnalyzeConnectedProjectJob.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/resources/ProjectsProviderUtils.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/telemetry/LinkTelemetry.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/assist/AssistCreatingAutomaticConnectionJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/assist/AssistCreatingManualConnectionJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/RulesConfigurationPageSaveJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/RulesConfigurationPage.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/SonarLintProjectPropertyPage.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/rule/RuleDetailsPanel.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/trim/StatusWidget.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/util/MessageDialogUtils.java
The existing message plugged into the saving of the local rules configuration was overhauled in phrasing. Additionally, a switch was added for users configuring it despite all projects already bound.
It was manually tested because Reddeer **always** expects [to come back to the main window after the preferences are closed](https://github.com/eclipse/reddeer/blob/master/plugins/org.eclipse.reddeer.jface/src/org/eclipse/reddeer/jface/preference/PreferenceDialog.java#L118-L120). It currently does not seem to support new shells popping up before the focus is back at the main window.
[THIS](https://github.com/eclipse/reddeer/issues/2227) issue was created. I've read in some threads that Reddeer is not maintained anymore but I didn't find anything official. Let's hope it is still maintained.
=> SLE-799: Overhaul rules configuration messaging

its/src/org/sonarlint/eclipse/its/AbstractSonarLintTest.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/preferences/SonarLintGlobalConfiguration.java
Some preferences persisted on the wrong level and were therefore interfering (but not breaking) some UI / UX stuff (e.g. notifications about Taint Vulnerabilities introduced).
This was re-evaluated and changed.
=> SLE-802: Re-evaluated the preference persistence

.cirrus.default.yml, .cirrus.ibuilds.yml
This is to be used as an intermediate solution. So we can continue with the optimization process on our side, we want to have build times that are not jumping up and down because Cirrus is choosing a build node type at random.
=> BUILD-4406: Consistent pipeline times

its/src/org/sonarlint/eclipse/its/SonarQubeConnectedModeTest.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/backend/SonarLintEclipseClient.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/RulesConfigurationPage.java
Some regressions from a faulty merge introduced removed changes on the connection assistance again.
A regression from SonarQube and the SonarText was fixed (not on our side) and we are able to enable the integration test again.
Additional changes for the issues with ITs and Reddeer. The implementation of the integration tests themselves will be handled in the separate pull request linked to [this PR](https://github.com/SonarSource/sonarlint-eclipse/commit/0752033174450d8f56431671f7e7fafd27407a98) and [SLE-799](https://sonarsource.atlassian.net/browse/SLE-799).
[SLE-799]: https://sonarsource.atlassian.net/browse/SLE-799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed issues based on regression

.github/workflows/release.yml
Split the old notification channel for the IntelliClipse squad
=> NO-JIRA: Change Slack channel

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/documentation/SonarLintDocumentation.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/command/HelpOnIconsCommand.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/AbstractBindingSuggestionPopup.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/SonarLintRpcClientSupportPopup.java
The Connected Mode page was split into informational and setup pages.
Additionally, the information displayed for Sloop being killed was fixed.
=> SLE-809: Update the outgoing links to documentation

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/SonarLintMarkerUpdater.java
Due to us now fetching all taints and not only the ones for the specific file, we were left with "leaked" markers when resolving / re-opening a taint.
This also led to multiple taint vulnerabilities being registered to different kinds of opened files, which was incorrect.
=> SLE-781: Fix leaking Taint Vulnerabilites

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java
It could happen randomly (mostly after running the unit tests), that the IDE froze because the SonarLint plug-in wasn't unloaded correctly. This was due to the thread waiting for Sloop to shut down - while it was already gone.
=> NO-JIRA: Don't wait for the backend

its/its-ibuilds.product, its/its.product, its/pom.xml, its/src/org/sonarlint/eclipse/its/AbstractSonarLintTest.java, its/target-platforms/ibuilds.target, its/target-platforms/latest.target, its/target-platforms/oldest.target, org.sonarlint.eclipse.core.tests/pom.xml, org.sonarlint.eclipse.core.tests/test.product, pom.xml, target-platforms/build.target
In order to have more "realistic" behavior of tests, we should switch to `p2Installed` mode for surefire.
This will allow to execute p2 touchpoints like a real installation.
See discussion: https://github.com/eclipse-tycho/tycho/discussions/3440
=> Update to Tycho 4.0.6 and provision tests with p2

.cirrus.default.yml, .cirrus/publish-dogfood-site.sh, .cirrus/site-resources/compositeArtifacts.xml, .cirrus/site-resources/compositeContent.xml
Instead of promoting the site artifact to sonarlint-eclipse-dogfood which is not publicly accessible, publish the site to https://binaries.sonarsource.com/?prefix=SonarLint-for-Eclipse/dogfood/
Manually tested with staging, see https://binaries-staging.sonarsource.com/?prefix=SonarLint-for-Eclipse/dogfood/
=> BUILD-3457 publish dogfood site on binaries

org.sonarlint.eclipse.site/pom.xml
The logic for signing ProtoBuf was incorrect and only signed the source OSGi bundle.
=> SLE-818: Sign ProtoBuf OSGi bundle

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/documentation/SonarLintDocumentation.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/preferences/SonarLintGlobalConfiguration.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/FileUtils.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/preferences/AbstractPathField.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/preferences/SonarLintPreferencePage.java
This will enable power users to configure SonarLint to use a specific Java 17+ JRE to run SonarLint out of process.
This is by default configured via the workspace settings but can be configured on the application level as well (not from the IDE).
=> SLE-822: Enable users to set JRE for Sloop

.cirrus/slack-notification.sh
The task name is now displayed instead of the id. Additionally the branch name is now more prominent.
=> SLE-816: Reworked the Slack notification

.github/workflows/release.yml
Updating the release workflow to 5.4.2 beta to verify the changes at https://github.com/SonarSource/gh-action_release/pull/186
=> BUILD-4839 Update release workflow to version 5.4.2 beta

.github/workflows/release.yml
Updating the release workflow to 5.5.0 beta to verify the changes at https://github.com/SonarSource/gh-action_release/pull/186
=> BUILD-4839 Update release workflow to 5.5.0

.github/workflows/release.yml
Release Action version 5.5.0 has been published. Update the release workflow to use the v5 branch for future updates. More details are at https://github.com/SonarSource/gh-action_release/releases.
=> BUILD-4839 Update release workflow to v5

.gitignore, pom.xml, target-platforms/commons.target
This uses the simplified artifact from https://github.com/SonarSource/sonarlint-core/pull/970. The simplification in the OSGI bundle should have no impact.
=> SLE-793: Use simplified SLCORE artifact

.cirrus.default.yml, .cirrus.ibuilds.yml
For unit tests, we need to upload not only the logs produced when running the tests but also the ones from Maven / Tycho produced while starting the *Junit Plug-In Tests* (the headless Eclipse instance that needs to be started in order to load the SonarLint plug-ins).
Also, don't fail/hang on logs that are not available on integration tests for SLE (the line was copied from IntelliJ by mistake).
=> NO-JIRA: Upload correct logs on unit tests

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/FileExclusionsChecker.java
The server exclusions are already handled by SLCORE. Checking them again locally could lead to some unexpected exceptions as well. Therefore, this is dropped in favor of what is already done in SLCORE.
=> SLE-874: Only check for local exclusions

org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/jobs/AnalyzeStandaloneProjectJobTest.java, org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/tests/common/SonarTestCase.java
Both these tests would either both succeed or fail. This is now decoupled.
Additionally, the events can take longer, so we have to wait for them. Due to us not being able to use the Awaitility library here (due to constrains of building Maven against latest Eclipse release with Java 11) we have to mimic that behavior. Please, see [SLE-883](https://sonarsource.atlassian.net/browse/SLE-883) for more information on that.
[SLE-883]: https://sonarsource.atlassian.net/browse/SLE-883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-883: Stabilize unit tests

.cirrus/publish-dogfood-site.sh
BUILD-5327 fix the CDN distribution ID retrieval in the dogfood publish script
=> BUILD-5327 fix CDN distribution ID index

.cirrus/publish-dogfood-site.sh
Improve the JMESPATH query to get it more generic (no specific index in the array of origins)
=> fix(BUILD-5327): generic JMESPATH to find cloudfront distribution ID

.cirrus/regular_mvn_build_deploy_analyze
SonarQube analysis will not contain **-SNAPSHOT** anymore and only the **{Major}.{Minor}.{Patch}** version; this will simplify the release process as well, not having to ask a champion to change the version on Next.
On SLE, we only have master, maintenance branches, and pull requests, removing unused code. The version on all available branches, including master and maintenance branches, looks like **{Major}.{Minor}.{Patch}-SNAPSHOT**
=> SLE-764: Simplified SonarQube analysis

.cirrus.default.yml
To avoid shipping two different versions, we have to check for consistency between the versions we pass to the Maven "pom.xml" file and the Eclipse PDE target platform "commons.target."
Sadly, it is not possible to set the version only once, as the target platform cannot be extended with a property or reference to another file or anything else.
[THIS](https://cirrus-ci.com/task/5553522060558336) was the test where I changed the version in the `target-platforms/commons.target` to differ from the one in the `pom.xml`, and it failed successfully! Ignore the point about the failing Slack notification, I have not fixed it yet on SLE but will do so later today, I fixed that on the other SL repos already :smile:
=> SLE-897: Consistency for SLCORE versions

.sonarlint/connectedMode.json
The Next instance was changed to only feature the non-redirect URL.
=> NO-JIRA: Shared Connected Mode

its/projects/secrets/secrets-custom/.project, its/projects/secrets/secrets-custom/Heresy.txt, its/res/custom-secrets.xml, its/src/org/sonarlint/eclipse/its/AbstractSonarQubeConnectedModeTest.java, its/src/org/sonarlint/eclipse/its/OpenInIdeTest.java, its/src/org/sonarlint/eclipse/its/SonarCloudConnectedModeTest.java, its/src/org/sonarlint/eclipse/its/SonarQubeConnectedModeTest.java, its/target-platforms/commons.target
In order to test custom secrets, the Sonar WS artifact had to be updated, with slight adjustments to some tests. Additionally, the move to SonarQube Enterprise from the orchestrator had to be done as the custom secrets are only available there.
=> SLE-798: Add IT for custom secrets

.cirrus.ibuilds.yml, org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/tracking/SonarLintMarkerUpdaterTest.java, target-platforms/ibuilds.target, target-platforms/latest-java-21.target
PyDev 12.1 was already prepared to be mirrored on the RE team side. Additionally, fix up the iBuilds Cirrus CI pipeline working with the new structure.
=> SLE-909: Update PyDev to 12.1 for newest target platforms

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/backend/SonarLintEclipseRpcClient.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/dialog/AwaitProjectConnectionReadyDialog.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/AbstractOpenInEclipseJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/OpenFixSuggestionInEclipseJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/OpenIssueInEclipseJob.java
In order to be able to re-use the logic of the "Open in IDE" feature for "Open fix suggestion" a small refactoring was required.
Due to recent changes regarding more and more Git logic moving to SLCORE, an additional flag was introduced to the `AbstractOpenInEclipseJob` for when less and less features rely on the Git logic of the IDE.
=> SLE-918: Refactor "Open in IDE" logic to be re-usable

its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/RulesConfigurationTest.java
Due to issues coming in asynchronously and the analysis being triggered differently with files changed and changes done to the preferences, this was overhauled to be less flaky. By opening / closing the file it is ensured that an analysis is triggered and therefore changes made in the preferences or via the context menu options, are handled in time and correctly.
=> SLE-922: Refactor rules configuration IT

its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/ConfirmManualAnalysisDialogOpened.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/EnhancedWithConnectedModeInformationDialogOpened.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/dialogs/ConfirmManualAnalysisDialog.java, its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/StandaloneAnalysisTest.java
[SLE-924](https://sonarsource.atlassian.net/browse/SLE-924)
All interactions with notifications and dialogs (shells) were not awaiting the shells to actually exist. This should now be fixed for all shells contributed by us. For the shells contributed by RedDeer itself (e.g., the project properties dialog), this is done on "their" side already.
Because all the implementations of `WaitCondition` are super big and mostly duplicated, I created a small task for the future (SLE-925) to de-duplicate it by creating a generic mother class. This is not part of this ticket, sprint, and release tho.
[SLE-924]: https://sonarsource.atlassian.net/browse/SLE-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-924: Refactor standalone analysis ITs

its/org.sonarlint.eclipse.its.connected.sc/src/org/sonarlint/eclipse/its/connected/sc/SonarCloudConnectedModeTest.java, its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/AbstractSonarQubeConnectedModeTest.java, its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/OpenInIdeTest.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/AbstractSonarLintTest.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/FileNotFoundDialogOpened.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/FixSuggestionAvailableDialogOpened.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/FixSuggestionUnavailableDialogOpened.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/ProjectSelectionDialogOpened.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/dialogs/ConfirmConnectionCreationDialog.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/dialogs/FileNotFoundDialog.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/dialogs/FixSuggestionAvailableDialog.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/dialogs/FixSuggestionUnavailableDialog.java, its/projects/connected-sc/sonarlint-its-sample-java-issues/.project, its/projects/connected-sc/sonarlint-its-sample-java-issues/FileExists.txt, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/assist/ConfirmSonarCloudConnectionCreationDialog.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/dialog/FixSuggestionAvailableDialog.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/AbstractOpenInEclipseJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/OpenIssueInEclipseJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/util/MessageDialogUtils.java, target-platforms/dev.target
In order to run RedDeer tests from the latest Eclipse IDE (that is running on top of Java 21), we also now have to use the Java 21-based Eclipse IDE as a reference in our development environment. I didn't notice it before as I developed against a dogfooding version of the Eclipse IDE that was powered by my locally installed Java 17 runtime.
Feedback from the PM was incorporated before implementing the ITs. To make it clearer, what was meant with button descriptions and notification titles displayed on failure. See the commit messages for more information.
A set of integration tests covering most of the cases by emulating a call from SonarCloud to the internal endpoint of SonarLint. This includes the default `file not found` as well as canceling, declining, and applying changes as well as …
=> SLE-923,SLE-927: Create ITs and incorporate validation feedback

its/org.sonarlint.eclipse.its.connected.sc/pom.xml, its/pom.xml, org.sonarlint.eclipse.core.tests/pom.xml
[SLE-926](https://sonarsource.atlassian.net/browse/SLE-926)
When running on macOS, we have to add a specific argument to make it usable, e.g., when running UTs/ITs on the command line. Noticed when running with Sophio that we had to adjust it all the time on her side.
[SLE-926]: https://sonarsource.atlassian.net/browse/SLE-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-926: macOS support for running in shell

org.sonarlint.eclipse.cdt/plugin.xml, org.sonarlint.eclipse.cdt/src/org/sonarlint/eclipse/cdt/internal/CProjectConfiguratorExtension.java, org.sonarlint.eclipse.cdt/src/org/sonarlint/eclipse/cdt/internal/CdtUtils.java
[SLE-930](https://sonarsource.atlassian.net/browse/SLE-930)
When working with CDT projects we don't want SonarLint to index the output directories containing the compiled source and possible generated Makefiles.
[SLE-930]: https://sonarsource.atlassian.net/browse/SLE-930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-930: Narrow down focus on CDT projects

its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/StandaloneAnalysisTest.java
[SLE-945](https://sonarsource.atlassian.net/browse/SLE-945)
This test was disabled following a faulty implementation regarding the check of symlinks and missing implementation regarding Windows shortcuts in SLCORE.
[SLE-945]: https://sonarsource.atlassian.net/browse/SLE-945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-945: Enable test with RSE again

org.sonarlint.eclipse.core/pom.xml, org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html, target-platforms/commons-its.target
[SLE-951](https://sonarsource.atlassian.net/browse/SLE-951)
[SLE-952](https://sonarsource.atlassian.net/browse/SLE-952)
[SLE-953](https://sonarsource.atlassian.net/browse/SLE-953)
[SLE-954](https://sonarsource.atlassian.net/browse/SLE-954)
[SLE-955](https://sonarsource.atlassian.net/browse/SLE-955)
[SLE-946](https://sonarsource.atlassian.net/browse/SLE-946)
Updated the analyzers as well as the release notes for the upcoming release.
Additionally, the `ProtoBuf` dependency needed an update for the ITs after it was updated on SLCORE prior to its release.
[SLE-951]: https://sonarsource.atlassian.net/browse/SLE-951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-952]: https://sonarsource.atlassian.net/browse/SLE-952?atlOrigin=eyJpIjoiNWRkNTljNz …
=> SLE-951,SLE-952,SLE-953,SLE-954,SLE-955,SLE-946: Update analyzers and prepare for release

org.sonarlint.eclipse.buildship/src/org/sonarlint/eclipse/buildship/internal/GradleUtils.java, org.sonarlint.eclipse.cdt/src/org/sonarlint/eclipse/cdt/internal/CdtUtils.java, org.sonarlint.eclipse.jdt/src/org/sonarlint/eclipse/jdt/internal/JdtUtils.java, org.sonarlint.eclipse.m2e/src/org/sonarlint/eclipse/m2e/internal/MavenUtils.java
[SLE-963](https://sonarsource.atlassian.net/browse/SLE-963)
Create a trace for the specific exclusions of JDT, Maven and Gradle (Eclipse Buildship) as well as CDT. This makes debugging easier.
For CDT also exclude the base directory and log on every configuration for every output directory as well.
[SLE-963]: https://sonarsource.atlassian.net/browse/SLE-963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-963: Log more on indexing exclusions and exclude base for CDT

its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/StandaloneAnalysisTest.java, its/projects/java/NoIndexSupport/.classpath, its/projects/java/NoIndexSupport/.project, its/projects/java/NoIndexSupport/.settings/org.eclipse.core.resources.prefs, its/projects/java/NoIndexSupport/.settings/org.eclipse.jdt.core.prefs, its/projects/java/NoIndexSupport/.settings/org.sonarlint.eclipse.core.prefs, its/projects/java/NoIndexSupport/src/hello/Hello.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/documentation/SonarLintDocumentation.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/FileSystemSynchronizer.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/preferences/SonarLintProjectConfiguration.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/preferences/SonarLintProjectConfigurationManager.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/resources/DefaultSonarLintProjectAdapter.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/SonarLintProjectPropertyPage.java
[SLE-967](https://sonarsource.atlassian.net/browse/SLE-967)
Users can opt-out per project from the indexing support (including exclusions) based on other Eclipse plug-ins like JDT/CDT/M2E/Buildship.
This should only be done in very specific cases; the information in the UI also provides this, and opting out should be assessed from project to project.
Cases are projects using Maven and also have source code in the "target" directory for example, and other corner cases (e.g. the performance is decreased because of the Gradle Tooling API version used transitively)!
I reached out to the squad to add a small paragraph to the [Troubleshooting](https://docs.sonarsource.com/sonarlint/eclipse/troubleshooting/) page explaining this and when it can be applied.
[SLE-967]: …
=> SLE-967: Users can opt-out of indexing support

.cirrus.default.yml, .cirrus.ibuilds.yml, .cirrus.star
[SLE-979](https://sonarsource.atlassian.net/browse/SLE-979)
1. Update cirrus-module v2 to v3.
2. Do not call the deprecated AWS feature method parameters `builder_subnet_id`.
3. It is recommended to not use `ec2_instance` or `eks_container` root keys.
[SLE-979]: https://sonarsource.atlassian.net/browse/SLE-979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-979 Migrate deprecated cirrus-module v2 to v3

README.md, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/documentation/SonarLintDocumentation.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/NotificationsWizardPage.java, pom.xml, target-platforms/commons-build.target
[SLE-993](https://sonarsource.atlassian.net/browse/SLE-993)
[SLE-998](https://sonarsource.atlassian.net/browse/SLE-998)
Fixes smart notification links in the Connection wizard and adds them to the general links class. Additionally, update to the released version of SLCORE.
[SLE-993]: https://sonarsource.atlassian.net/browse/SLE-993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SLE-998]: https://sonarsource.atlassian.net/browse/SLE-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-993,SLE-998: Fix smart notification links and update SLCORE

.cirrus.default.yml
[SLE-1001](https://sonarsource.atlassian.net/browse/SLE-1001)
This is done by other repos as well for now until Orchestrator is fixed.
[SLE-1001]: https://sonarsource.atlassian.net/browse/SLE-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1001 Use fixed development reference for SQ instead of version number

.cirrus/Dockerfile, .gitignore, its/org.sonarlint.eclipse.its.connected.sc/its.connected.sc.product, its/org.sonarlint.eclipse.its.connected.sc/src/org/sonarlint/eclipse/its/connected/sc/SonarCloudConnectedModeTest.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/conditions/CFamilyLoaded.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/perspectives/CppPerspective.java, its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/RuleDescriptionViewTest.java, its/projects/cdt/MakefileProject/.cproject, its/projects/cdt/MakefileProject/.project, its/projects/cdt/MakefileProject/.settings/language.settings.xml, its/projects/cdt/MakefileProject/Makefile, its/projects/cdt/MakefileProject/hello.c
[SLE-969](https://sonarsource.atlassian.net/browse/SLE-969)
Using simple Makefile-based project for testing the C analysis and configuration in the sub-module.
Additionally, updated the CI components to provide all tools for using gcc/g++/make with Eclipse CDT. A few changes were also necessary as the CI image hasn't been rebuild in months and now misses the WebKit libraries necessary for rendering the SWT browser instance - this is fixed!
[SLE-969]: https://sonarsource.atlassian.net/browse/SLE-969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-969: Create integration test with CDT

NOTICE.txt
[SLE-999](https://sonarsource.atlassian.net/browse/SLE-999)
Incorporate the information that packaged analyzers are now under SSAL.
[SLE-999]: https://sonarsource.atlassian.net/browse/SLE-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-999: Update NOTICE.txt

its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/RuleDescriptionViewTest.java
[SLE-928](https://sonarsource.atlassian.net/browse/SLE-928)
Instead of testing the same value every time, for every iteration, we check the new value and then check it.
[SLE-928]: https://sonarsource.atlassian.net/browse/SLE-928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-928: Await Rule Description content correctly

README.md, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/documentation/SonarLintDocumentation.java, org.sonarlint.eclipse.feature/feature.properties, org.sonarlint.eclipse.feature/feature.xml, org.sonarlint.eclipse.site/category.xml, org.sonarlint.eclipse.ui/about.properties, org.sonarlint.eclipse.ui/intro/tutorialsExtensionContent.xml, pom.xml
[SLE-988](https://sonarsource.atlassian.net/browse/SLE-988)
The user facing links to the SonarQube for IDE: Eclipse documentation are updated.
[SLE-988]: https://sonarsource.atlassian.net/browse/SLE-988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-988: Update links to the documentation

.cirrus.default.yml, .cirrus.ibuilds.yml
[SLE-1003](https://sonarsource.atlassian.net/browse/SLE-1003)
Some tasks were hitting their CPU limit and needed more power, some tasks were running OOM sometimes because they needed more memory.
For some tasks having too many CPUs or too much memory assigned this was finetuned as well.
[SLE-1003]: https://sonarsource.atlassian.net/browse/SLE-1003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1003: Reassess CPU / memory for tasks

.cirrus.default.yml, its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/SonarQubeConnectedModeTest.java, its/pom.xml, org.sonarlint.eclipse.core/pom.xml, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java, org.sonarlint.eclipse.ui/intro/RELEASE_NOTES.html, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/AbstractOpenInEclipseJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/OpenFixSuggestionInEclipseJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/job/OpenIssueInEclipseJob.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/util/MessageDialogUtils.java, pom.xml, target-platforms/commons-build.target, target-platforms/commons-its.target
[SLE-986](https://sonarsource.atlassian.net/browse/SLE-986)
[SLE-986]: https://sonarsource.atlassian.net/browse/SLE-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-986: Update Parent POM, Release Notes, SLCORE

.cirrus.default.yml, .cirrus.ibuilds.yml, .cirrus/Dockerfile, .cirrus/settings-public-auth.xml, its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/SonarQubeConnectedModeTest.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/preferences/FileAssociationsPreferences.java, target-platforms/ibuilds.target, target-platforms/latest-java-17_e431.target, target-platforms/latest-java-21.target, target-platforms/oldest-java-11_e48.target
=> EREQ-85 Use Repox mirror of Reddeer after termination of project at Eclipse

org.sonarlint.eclipse.core/META-INF/MANIFEST.MF, org.sonarlint.eclipse.ui/META-INF/MANIFEST.MF, pom.xml, target-platforms/commons-build.target
[SLE-1030](https://sonarsource.atlassian.net/browse/SLE-1030)
[SLE-1030]: https://sonarsource.atlassian.net/browse/SLE-1030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1030 Bump core version to 10.12.1 (drop Bearer auth with SQ 10.0 to 10.3)

its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/AbstractSonarQubeConnectedModeTest.java, its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/SonarQubeConnectedModeTest.java
[SLE-1032](https://sonarsource.atlassian.net/browse/SLE-1032)
Username/password authentication was removed from the UI and the authentication is now also unavailable for SQ-S 2025 LTA. The ITs have been adjusted.
[SLE-1032]: https://sonarsource.atlassian.net/browse/SLE-1032?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1032: Remove `sonar.password` from SQ-S ITs

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/preferences/SonarLintGlobalConfiguration.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintUiPlugin.java
[SLE-1020](https://sonarsource.atlassian.net/browse/SLE-1020)
Prior to this change it was shown every day until the user updated to a new version or when the internal system property was not used.
[SLE-1020]: https://sonarsource.atlassian.net/browse/SLE-1020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1020: Only show new version hint every two weeks

.cirrus.default.yml, its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/RuleDescriptionViewTest.java, its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/StandaloneAnalysisTest.java, its/pom.xml, target-platforms/oldest-java-11_e417.target
[SLE-1041](https://sonarsource.atlassian.net/browse/SLE-1041)
Move from 4.8 (Photon) to 4.17 (2020-09) as the minimal targeted version for ITs.
When the next version will be released, the actual "guard" will be put in place on the Eclipse Marketplace. Otherwise there is no strict guard build in place as the Eclipse Core / Runtime / UI plug-ins are not strictly bound to a Eclipse IDE version released.
[SLE-1041]: https://sonarsource.atlassian.net/browse/SLE-1041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1041: Change oldest target definition

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/ReleaseNotesPopup.java
[SLE-1044](https://sonarsource.atlassian.net/browse/SLE-1044)
This pop-up still contained "SonarLint" and needed an update. For users coming from very old versions, we still contain the info that this plug-in used to be called "SonarLint".
[SLE-1044]: https://sonarsource.atlassian.net/browse/SLE-1044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1044: Update/released pop-up with SonarQube for Eclipse

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/ConfigScopeSynchronizer.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/preferences/SonarLintProjectConfigurationManager.java
[SLE-1050](https://sonarsource.atlassian.net/browse/SLE-1050)
This was causing errors from SLCORE as the preferences were receiving events after the project was removed.
[SLE-1050]: https://sonarsource.atlassian.net/browse/SLE-1050?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1050: Remove binding properties listener appropriately

its/org.sonarlint.eclipse.its.connected.sc/src/org/sonarlint/eclipse/its/connected/sc/SonarCloudConnectedModeTest.java, its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/AbstractSonarLintTest.java, org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/jobs/AnalyzeStandaloneProjectJobTest.java, org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/resources/SonarLintProjectConfigurationManagerTest.java, org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/tracking/SonarLintMarkerUpdaterTest.java, org.sonarlint.eclipse.core.tests/src/test/java/org/sonarlint/eclipse/core/internal/utils/DurationUtilsTest.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/SonarLintLogger.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/LogListener.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/preferences/SonarLintGlobalConfiguration.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintUiPlugin.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/console/SonarLintConsole.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/popup/ErrorPopup.java
[SLE-1065](https://sonarsource.atlassian.net/browse/SLE-1065)
When a user decide to ignore an error, also ignore "similar" errors. Also give the user the opportunity to not show any error notifications again.
Therefore the logging logic was overhauled (which I would have to do anyway for a proper error reporting mechanism that is planned to be implemented later).
[SLE-1065]: https://sonarsource.atlassian.net/browse/SLE-1065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1065: Overhaul error notification

org.sonarlint.eclipse.ui/plugin.xml
[SLE-1068](https://sonarsource.atlassian.net/browse/SLE-1068)
For easier onboarding of users we add the SonarQube views to the C/C++ and PDE perspective as well. In order to raise awareness with Connected Mode, the Bindings view was added to all perspectives as well.
See the screenshots appended to the ticket on how this looks like now. This is added to the perspectives initially and not every time - so it is helping the onboarding :partying_face: 
[SLE-1068]: https://sonarsource.atlassian.net/browse/SLE-1068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1068: Add SonarQube views to other perspectives

.gitignore, its/org.sonarlint.eclipse.its.cdt/ITs CDT.launch, its/org.sonarlint.eclipse.its.connected.sc/ITs SQ-C.launch, its/org.sonarlint.eclipse.its.connected.sq/ITs SQ-S.launch, its/org.sonarlint.eclipse.its.connected.sq/src/org/sonarlint/eclipse/its/connected/sq/SonarQubeConnectedModeTest.java, its/org.sonarlint.eclipse.its.standalone/ITs Standalone.launch, org.sonarlint.eclipse.core.tests/Unit Tests.launch, org.sonarlint.eclipse.core/Eclipse IDE SQ-C Staging.launch, org.sonarlint.eclipse.core/Eclipse IDE.launch, sonarlint-java-client-osgi.launch
[SLE-1090](https://sonarsource.atlassian.net/browse/SLE-1090)
Add launcher for running the Eclipse IDE, including the configuration for SonarQube Cloud Staging. Also, add launcher to run unit/integration tests.
An additional launcher for fixing the SonarLint Core OSGi bundle version for the target platforms was added that relies on the local OS command `find`.
[SLE-1090]: https://sonarsource.atlassian.net/browse/SLE-1090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1090: Introduce development/testing launcher

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/FileSystemSynchronizer.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/resources/DefaultSonarLintProjectAdapter.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/SonarLintUtils.java
[SLE-1098](https://sonarsource.atlassian.net/browse/SLE-1098)
See the actual Jira ticket for more information.
Eclipse PDE alongside Maven/Tycho has a bug when using Target Platform definitions and `product` definition files in a project, that a folder is created named `file:` that contains unpacked parts of plug-ins. This triggers a lot of events every time something changes - it consumes a lot of bandwidth and should therefore be ignored.
[SLE-1098]: https://sonarsource.atlassian.net/browse/SLE-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1098: Exclude buggy Eclipse PDE files

.cirrus.default.yml, its/org.sonarlint.eclipse.its.connected.sq/its.connected.sq.product, target-platforms/latest-java-17_e431.target
[SLE-1113](https://sonarsource.atlassian.net/browse/SLE-1113)
Don't rely on the latest Eclipse Mylyn version for the latest Java 17 based target platform but the one linked to that Eclipse IDE release.
Consequence is that the actual feature name of Mylyn is inconsistent and had to be updated in the `product` definition of the Connected Mode ITs against SonarQube Server (all running with Java 17).
The Standalone Mode ITs on the CI also don't run against Java 17 anymore as we are testing both the oldest and the newest supported version, this was a leftover of July last year when the Eclipse IDE moved from Java 17 to 21.
[SLE-1113]: https://sonarsource.atlassian.net/browse/SLE-1113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1113: Rely on Eclipse Mylyn of released version

pom.xml
[SLE-1109](https://sonarsource.atlassian.net/browse/SLE-1109)
For the SonarQube Server analysis we require a new property to tweak the Bill of Material generation that is currently not working with Maven/Tycho out of the box.
For more context, see [this thread](https://discuss.sonarsource.com/t/bom-does-not-work-for-maven-tycho-builds/21816).
[SLE-1109]: https://sonarsource.atlassian.net/browse/SLE-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1109: Add option for BOM to work correctly with Tycho

its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/FileExclusionsTest.java, its/projects/java/TestOutputEqualsProject/.classpath, its/projects/java/TestOutputEqualsProject/.project, its/projects/java/TestOutputEqualsProject/.settings/org.eclipse.core.resources.prefs, its/projects/java/TestOutputEqualsProject/.settings/org.eclipse.jdt.core.prefs, its/projects/java/TestOutputEqualsProject/Test.py, its/projects/java/TestOutputEqualsProject/src/aaa/Main.java, org.sonarlint.eclipse.jdt/src/org/sonarlint/eclipse/jdt/internal/JdtUtils.java
[SLE-1125](https://sonarsource.atlassian.net/browse/SLE-1125)
When a JDT project has configured the default output directory to point to the project / base directory, don't exclude the whole project from indexing and the analysis.
Added an integration test to mimic such a corner case and to see that it still behaves correctly.
[SLE-1125]: https://sonarsource.atlassian.net/browse/SLE-1125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1125: Handle index exclusions correctly with JDT

its/org.sonarlint.eclipse.its.cdt/ITs CDT.launch, its/org.sonarlint.eclipse.its.connected.sc/ITs SQ-C EU.launch, its/org.sonarlint.eclipse.its.connected.sc/ITs SQ-C US.launch, its/org.sonarlint.eclipse.its.connected.sq/ITs SQ-S.launch, its/pom.xml, org.sonarlint.eclipse.core.tests/Unit Tests.launch, org.sonarlint.eclipse.core.tests/pom.xml
[SLE-1122](https://sonarsource.atlassian.net/browse/SLE-1122)
Sentry should only gather data on production environments and should not be polluted by UTs/ITs (running locally or on the CI).
[SLE-1122]: https://sonarsource.atlassian.net/browse/SLE-1122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1122: Don't pollute Sentry when running UTs/ITs

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/SonarLintUtils.java
[SLE-1133](https://sonarsource.atlassian.net/browse/SLE-1133)
We currently exclude files from VCS, Node.js and Python virtual environments from indexing (and therefore the analysis) to optimize our plug-in.
We should do it correctly by checking for the actual files and folder and not whether an excluded identifier is part of the string of the absolute path.
[SLE-1133]: https://sonarsource.atlassian.net/browse/SLE-1133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1133: Correctly exclude files from indexing

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintImages.java
[SLE-1134](https://sonarsource.atlassian.net/browse/SLE-1134)
When moving between the old and new severity icons for Standard Mode it was missed to correctly handle the grouping icons which currently falls back to the one of the information severity.
[SLE-1134]: https://sonarsource.atlassian.net/browse/SLE-1134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1134: Show correct legacy Severity grouping icons

pom.xml
[SLE-1137](https://sonarsource.atlassian.net/browse/SLE-1137)
This improves the UX for our SonarQube for Eclipse developers when importing the Maven projects into the IDE. This applies the [official documentation](https://eclipse.dev/m2e/documentation/m2e-making-maven-plugins-compat.html) to Maven.
[SLE-1137]: https://sonarsource.atlassian.net/browse/SLE-1137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1137: Automatic Lifecycle Mappings for Maven

.gitattributes
[SLE-1147](https://sonarsource.atlassian.net/browse/SLE-1147)
Make sure all files used for unit tests have LF as EOL. This should prevent the unit tests to fail on Windows machines.
[SLE-1147]: https://sonarsource.atlassian.net/browse/SLE-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1147 Make sure all files used for unit tests have LF as EOL.

its/org.sonarlint.eclipse.its.connected.sc/src/org/sonarlint/eclipse/its/connected/sc/SonarCloudConnectedModeTest.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/AbstractConnectionWizard.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/ServerConnectionWizard.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/binding/wizard/connection/SuggestConnectionWizard.java
[SLE-803](https://sonarsource.atlassian.net/browse/SLE-803)
The organization is not taken into account when checking for the token anymore, which led to incorrect behavior and rendered the wizard unusable.
[SLE-803]: https://sonarsource.atlassian.net/browse/SLE-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-803: Invalid organization should not render wizard unusabled

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/SonarLintBackendService.java
[SLE-1148](https://sonarsource.atlassian.net/browse/SLE-1148)
This was removed a while ago due to flakyness and it sometimes prevented the IDE from shutting down as it was waiting for SonarQube for Eclipse. Let's introduce it again and see.
[SLE-1148]: https://sonarsource.atlassian.net/browse/SLE-1148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1148: Wait for SLOOP to shutdown gracefully

target-platforms/oldest-java-11_e417.target
[SLE-1130](https://sonarsource.atlassian.net/browse/SLE-1130)
Despite this being the oldest Eclipse IDE we support, build with Java 11, we run the ITs on a Java 17 runtime to make use of the Eclipse RedDeer 4.7.1 (forked version).
And with that we only have to maintain the one version of the Eclipse RedDeer fork :partying_face: 
[SLE-1130]: https://sonarsource.atlassian.net/browse/SLE-1130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1130: Rely on Java 17 and RedDeer 4.7.1 for oldest ITs

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/TriggerType.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/markers/ApplyQuickFixMarkerResolver.java
[SLE-1157](https://sonarsource.atlassian.net/browse/SLE-1157)
This does not make sense due to the fact that when applying a quick fix the file is not saved and therefore the analysis runs on the pre-quick-fix-applied file.
This is a useless analysis. And in anticipation of the upcoming changes to the analysis triggering API of SonarLint Core this is removed to have less confusion.
[SLE-1157]: https://sonarsource.atlassian.net/browse/SLE-1157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1157: Don't analyze when a quick fix was applied

its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/AbstractSonarLintTest.java, its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/FileExclusionsTest.java, its/projects/UnsupportedCharset/.project, its/projects/UnsupportedCharset/a.py, its/projects/UnsupportedCharset/din_66003.xml, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/backend/FileSystemSynchronizer.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/resources/DefaultSonarLintProjectAdapter.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/utils/SonarLintUtils.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/resource/ISonarLintFile.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/util/PlatformUtils.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/util/SelectionUtils.java
When a file is in the project with an unsupported charset (or encoding) it should be excluded from indexing and the analysis. This should not impact other files or part of the experience.
Added an IT to test that everything still works as expected.
This is a adjusted PR for triggering the CI for the external contribution coming from #832
=> SLE-1121: Exclude files with unsupported charset (or encoding)

its/org.sonarlint.eclipse.its.shared/src/org/sonarlint/eclipse/its/shared/reddeer/preferences/AnalyzerPropertiesPreferences.java, its/org.sonarlint.eclipse.its.standalone/src/org/sonarlint/eclipse/its/standalone/AnalyzerPropertiesTest.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/preferences/SonarLintGlobalConfiguration.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/properties/SonarLintExtraArgumentsPreferenceAndPropertyPage.java
[SLE-1159](https://sonarsource.atlassian.net/browse/SLE-1159)
When the analysis properties are changed for either the project or globally, trigger a new (automatic) analysis of the opened files to refresh based on the user changes.
[SLE-1159]: https://sonarsource.atlassian.net/browse/SLE-1159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1159: Trigger analysis of opened files on analysis properties change

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/SonarLintRpcClientSupportService.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/issues/MarkerViewWithBottomPanel.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/issues/OnTheFlyIssuesView.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/issues/SonarLintReportView.java, org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/issues/TaintVulnerabilitiesView.java
[SLE-1166](https://sonarsource.atlassian.net/browse/SLE-1166)
Don't share the instance of `MarkerViewWithBottomPanel` that was always the latest view initialized. Also dispose the view correctly as otherwise this would have triggered a exception when the instance was still around but the views were closed.
[SLE-1166]: https://sonarsource.atlassian.net/browse/SLE-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1166: Don't share the instance and dispose marker views correctly

org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/analysis/IAnalysisConfigurator.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/analysis/IPostAnalysisContext.java, org.sonarlint.eclipse.core/src/org/sonarlint/eclipse/core/internal/jobs/AnalyzeProjectJob.java
[SLE-1167](https://sonarsource.atlassian.net/browse/SLE-1167)
Since the analysis is asynchronous nowadays, the "AnalyzeProjectJob#analysisCompleted" did not make sense anymore - as the analysis request was only handed over to SLCORE, but not finished.
The extension point method in the background did not make sense anymore and should be replaced on the implementing side (e.g. by a scheduled cleanup). The related logic for that was therefore deprecated to be removed with the next major release.
| Extension point | Method | Removed or added? | Why? |
| --- | --- | --- | --- |
|  *org.sonarlint.eclipse.core.analysisConfigurator* | [org.sonarlint.eclipse.core.analysis.IAnalysisConfigurator#analysisComplete(IPostAnalysisContext, IProgressMonitor)](https://github.com/SonarSource/sonarlint-eclipse …
=> SLE-1167: Remove analysis completion method and deprecate EP

org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/util/PlatformUtils.java
[SLE-1185](https://sonarsource.atlassian.net/browse/SLE-1185)
When using a Eclipse-based application (like specific IDEs) that does not provide the _Welcome_ view at all or not the intro page we extend (what's new / overview page) and that is opened by default by the _Welcome_ view, we should not throw a unhandled runtime exception. In those and other cases, just not open the _Welcome_ view.
Here a screenshot of what it looks like without the change:
And here are the corresponding Error Log ([Error.log](https://github.com/user-attachments/files/20107307/Error.log)) and the Runtime Error ([Runtime.log](https://github.com/user-attachments/files/20107310/Runtime.log)).
[SLE-1185]: https://sonarsource.atlassian.net/browse/SLE-1185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
=> SLE-1185 Handle the failure to open the Welcome page more gracefully

pom.xml
[SLE-1181](https://sonarsource.atlassian.net/browse/SLE-1181)
`sonar.sca.excludedManifests` is deprecated in SQS 2025.3 and is replaced with `sonar.sca.exlusions`. The behavior is exactly the same, this is just a rename to better match other sonar properties.
[SLE-1181]: https://sonarsource.atlassian.net/browse/SLE-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SLE-1181 chore: use the renamed sonar.sca.exclusions property

.github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml
[BUILD-8875](https://sonarsource.atlassian.net/browse/BUILD-8875)
This PR updates GitHub Actions workflows to use our new standardized runner naming convention.
- Updates runner names in workflow files to new standardized format
- No functional changes to your CI/CD pipelines
- All existing functionality remains identical
| Old Runner | New Runner |
|------------|------------|
| sonar-runner-large | github-ubuntu-latest-s |
| ubuntu-latest-large | github-ubuntu-latest-s |
| windows-latest-large | github-windows-latest-s |
| ubuntu-24.04-large | github-ubuntu-latest-s |
| sonar-runner-large-arm | github-ubuntu-24.04-arm-s |
| ubuntu-24.04-arm-large | github-ubuntu-24.04-arm-s |
1. Review the changes in this PR
2. Merge when ready - no additional action required
3. Old runners will remain …
=> BUILD-8875: Migrate to standardized GitHub runner names
